### ISSUE TITLE
doubtful segment id in bi-vb-sk

### ISSUE THREAD

**Issue by yapcheahshen** [suttacentral/bilara-data#10]
pli-tv-bi-vb-sk1-75_root-pli-ms.json
pli-tv-bi-vb-sk1:75:0.1  should be pli-tv-bi-vb-sk75:0.1
pli-tv-bi-vb-sk1:75:0.2  should be pli-tv-bi-vb-sk75:0.2

pli-tv-bi-vb-sk1-75_translation-en-brahmali.json
  "pli-tv-bi-vb-sk1:75:0.1": "The sub-chapter on shoes ",
  "pli-tv-bi-vb-sk1:75:0.2": "75. the training rule on defecating in water ",

**Comment by sujato** [comment]
I've checked this and it seems correct.
