### ISSUE TITLE
Two segments in Vinaya blurbs wrongly placed/named

### ISSUE THREAD

**Issue by sabbamitta** [suttacentral/bilara-data#1061]
In the Bilara interface of `pli-tv-bu-**vb**-blurbs_translation-de-blurb`, the first two segments, `pli-tv-bu-vb-sk` and `pli-tv-bu-vb-sk69`, are in the wrong place. They belong at the end of the file, not the beginning. When translating them, the text shows up in `pli-tv-bu-**pm**-blurbs_translation-de-blurb`.

In the Bilara interface of `pli-tv-bu-**pm**-blurbs_translation-de-blurb`, these two segments are correctly at the end of the file, but have the wrong names. Instead of `pli-tv-bu-**pm**-sk` and `pli-tv-bu-**pm**-sk69`, they are called `pli-tv-bu-**vb**-sk` and `pli-tv-bu-**vb**-sk69`.

The segments should be in both files, at the end, and with their correct names.

See discussion on Gitter of Oct. 21, 2021.

**Comment by sujato** [comment]
This issue was caused by two misnamed segments in `pli-tv-bu-vb-blurbs_root-en.json`. I have fixed them and the issue should be resolved.
