### ISSUE TITLE
Duplicate names segment_ids and confusion

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/bilara-data#1077]
I do not understand how all the names system works, except that names is older than super-names.

In some cases there are problematic entries, for example:
```
./root/misc/site/name/super-name_root-misc-site.json
141:  "super-name:140.lzh-sarv-bu-kam": "Bhikkhu Kammavācā (1st)",
142:  "super-name:141.lzh-sarv-bu-kam-2": "Bhikkhu Kammavācā (2nd)",

./root/misc/site/name/vinaya/lzh-sarv-bu-kam-2-name_root-misc-site.json
2:  "lzh-sarv-bu-kam-2-name:1.lzh-sarv-bu-kam-2": "Bhikkhu Kammavācā (2nd)"

./root/misc/site/name/vinaya/lzh-sarv-bu-kam-name_root-misc-site.json
2:  "lzh-sarv-bu-kam-name:1.lzh-sarv-bu-kam": "Bhikkhu Kammavācā"
```
In some cases the "site/name" entries are actually corrupt, with a `{}` instead of a string:

```
./root/misc/site/name/super-name_root-misc-site.json
126:  "super-name:125.lzh-dg-bu-kam-2": "Bhikkhu Kammavācā (2nd)",

./root/misc/site/name/vinaya/lzh-dg-bu-kam-2-name_root-misc-site.json
2:  "lzh-dg-bu-kam-2-name:1.lzh-dg-bu-kam-2": {}
```

I believe that this issue would be resolved by purging any entry from a non-supernames file if it also appears in a supernames file.

**Comment by sujato** [comment]
Ahh okay, thanks.

Normally the `super-name` is the higher-order name ("superstructure"), and the `name` files include things underneath that. So typically you'd have a nikaya in the supername, the the pannasas, vaggas, etc. in the `name` files.

These problems arise when you have simple texts that lack internal structure, so there is no real need for a `name` file.

I've deleted the unneeded files, and fixed the following:

- corrupt files with {}
- nested name files
- corrupt files with "object"

Here's the commit to `unpublished`:

https://github.com/suttacentral/bilara-data/commit/738ba74646da52c42eded17f910c34fd42f66dbe

We should probably cherrypick this commit to push t published.
