### ISSUE TITLE
Files deleted in `bilara-data` are still present in `sc_bilara_data`

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#1081]
Currently `make load-data` generates an extensive list of "duplicate IDs". The underlying problem is that the files have been deleted in `bilara-data`, but the deleted files are retained in `sc_bilara_data`. 

We should ensure that when files are deleted in `bilara-data`, the corresponding files are also deleted in `sc_bilara_data` when the GA copies them over.

**Comment by blake-sc** [comment]
So I've deleted the problematic files that currently exist, but the other half of the issue, the automated deletion of deleted files, remains open.

**Comment by ccronje** [comment]
I think @dayunbao has fixed this. I deleted a few files in `bilara-data` yesterday and they were automatically deleted from `sc_bilara_data`.
