### ISSUE TITLE
Incorrect breaks in Pali MN.004

### ISSUE THREAD

**Issue by HarDao** [suttacentral/bilara-data#1151]
Now it is:

2.8
“Durabhisambhavāni hi kho, bho gotama, araññavanapatthāni pantāni senāsanāni, dukkaraṁ pavivekaṁ, durabhiramaṁ

2.9
ekatte, haranti maññe mano vanāni samādhiṁ alabhamānassa bhikkhuno”ti.

Should be:

2.8
“Durabhisambhavāni hi kho, bho gotama, araññavanapatthāni pantāni senāsanāni, dukkaraṁ pavivekaṁ, durabhiramaṁ ekatte,

2.9
haranti maññe mano vanāni samādhiṁ alabhamānassa bhikkhuno”ti.

+

Now:

2.11
Durabhisambhavāni hi kho, brāhmaṇa, araññavanapatthāni pantāni senāsanāni, dukkaraṁ pavivekaṁ, durabhiramaṁ ekatte, haranti maññe mano vanāni samādhiṁ alabhamānassa bhikkhuno.

Should be (probably):

2.11
Durabhisambhavāni hi kho, brāhmaṇa, araññavanapatthāni pantāni senāsanāni, dukkaraṁ pavivekaṁ, durabhiramaṁ ekatte,

2.12
haranti maññe mano vanāni samādhiṁ alabhamānassa bhikkhuno.

Now:

3.2
‘durabhisambhavāni hi kho araññavanapatthāni pantāni senāsanāni, dukkaraṁ pavivekaṁ, durabhiramaṁ

3.3
ekatte, haranti maññe mano vanāni samādhiṁ alabhamānassa bhikkhuno’ti.

Should be:
3.2
‘durabhisambhavāni hi kho araññavanapatthāni pantāni senāsanāni, dukkaraṁ pavivekaṁ, durabhiramaṁ ekatte,

3.3
haranti maññe mano vanāni samādhiṁ alabhamānassa bhikkhuno’ti.

**Comment by sujato** [comment]
Thanks, that's well-spotted!

I've made these fixes now. Please let me know if you find any more.

You might get a quicker response by posting on our forum:

https://discourse.suttacentral.net/t/fill-us-with-happiness-tell-us-about-all-our-mistakes/25453
