### ISSUE TITLE
Incorrect breaks in Pali in MN.007

### ISSUE THREAD

**Issue by HarDao** [suttacentral/bilara-data#1162]
Now it is:

5.1
Yato kho, bhikkhave, bhikkhuno ‘abhijjhāvisamalobho cittassa upakkileso’ti—

5.2
iti viditvā abhijjhāvisamalobho cittassa upakkileso pahīno hoti, ‘byāpādo cittassa upakkileso’ti—

Should be (just like in 4.1 + 4.2)

5.1
Yato kho, bhikkhave, bhikkhuno ‘abhijjhāvisamalobho cittassa upakkileso’ti—iti viditvā abhijjhāvisamalobho cittassa upakkileso pahīno hoti, 

5.2
‘byāpādo cittassa upakkileso’ti—

**Comment by sujato** [comment]
well-spotted, thanks, I have fixed it.
