### ISSUE TITLE
Confusion of headings in German translation of Kd6

### ISSUE THREAD

**Issue by sabbamitta** [suttacentral/bilara-data#1238]
Beginning from 17. Ambapālīvatthu, there is a confusion of headings in this Khandhaka.

What here is chapter 17 should be 17 + 18 (in English, there are two levels of headings: 17 & 18, and then sub-headings 17 and 18).

What should be chapter 19 is then called chapter 18 in German, and so on.

**Comment by sabbamitta** [comment]
Headings should be:
- `17. Ambapālīvatthu` is still correct (starts with M-T1~124)
- `18. Licchavīvatthu` has to come before M-T3~126
- `19. Sīhasenāpativatthu` has to replace `18. Licchavīvatthu`
- `20. Kappiyabhūmianujānanā` has to replace `19. Sīhasenāpativatthu`
- `21. Meṇḍakagahapativatthu` is again correct
- `22. Pañcagorasādianujānana` has to go one paragraph further down, to M-T17~165
- `23. Keṇiyajaṭilavatthu` is correct
- `24. Rojamallavatthu` is correct
- `25. Vuḍḍhapabbajitavatthu` is correct
- `26. Catumahāpadesakathā` is correct

Finished.

**Comment by ccronje** [comment]
Thanks @sabbamitta
