### ISSUE TITLE
editing interface for JSON configuration data

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#1285]
Currently our data such as `_publication.json`, etc., is edited manually. This is error-prone, and also make it hard to visualize the data and its relationships. For example, if I want to know, "do all entries have a field for XYZ" it's not easy to say. This data is hand-edited by volunteers, and I'd like to make their life a bit easier. As the amount of publications increases, the size and complexity of the JSON files will increase and the problem will become more acute. 

## solution

Let's set up our configuration data to use with a spreadsheet or similar. We can then export JSON files as TSV, edit them in a spreadsheet, and import them back into bilara-data.

This will depend on first flattening our JSON data.

https://github.com/suttacentral/bilara-data/issues/596

**What we're looking for is a lightweight solution for a simple problem. It's just a convenience for our volunteers. Did I mention keep it simple?**

The basic process is something like this:

-  convert JSON file on Github to TSV
- import the TSV to a google sheet (or similar)
- edit it
- convert it back to JSON
- update the Github file

## possible approaches

- use bilara i/o as interface? (probably not, see Blake's comment below)
- use an off-the-shelf web interface?
- do it ourself

## examples

Here are some services that do this kind of thing.

https://sheet2api.com/google-sheet-to-json-api/

https://gist.github.com/ronaldsmartin/47f5239ab1834c47088e

https://qmacro.org/2013/10/04/sheetasjson-google-spreadsheet-data-as-json/

**Comment by blake-sc** [comment]
Do I understand this correctly that you want to be able to transform _publication.json and other underscore json files to/from TSV to permit editing in a spreadsheet.

This isn't really a job for bilara-io which does very specific things. However the task of converting well structured json to/from TSV is exceedingly trivial for a python script.

**Comment by sujato** [comment]
Yes, this is correct. Using Bilara i/o is just an implementation suggestion. I'll change the framing of the issue.

Perhaps it would be better to use an off-the-shelf web integration?

Or do you have a suggestion how to do it?

**Comment by blake-sc** [comment]
So my implementation thoughts.

Bilara client is pretty easy to add new views to, so we create an admin view, that is linked to from the top bar or the home page.

Bilara server knows who is logged in and what their permissions are on Github, anyone with admin permissions for bilara-data can just be an admin in the bilara app too. Technically anyone with write permission to bilara-data can freely modify those files, but I think we'll stick with admin permission just to avoid confusion/temptation.

Bilara server needs a few modifications:

* It needs to inform the client whether or not the user is an admin probably as part of the login process.
* It needs an API endpoint which returns a list of config files which can be edited in the bilara admin interface.
* And then API GET/POST endpoints to get the data for and set the data for config files.
* The actual conversion from flat JSON to a spreadsheet format is trivial, and if it's not done by the Spreadsheet library automatically, it's pretty much a one liner with the python csv library.
* Config files should generally be kept in sync between published and unpublished branch: however we might consider having only _project.json exist in unpublished and no other config files (bilara app gets most its config from Github), and having _project.json not exist in published, making _project.json the exclusive configuration file for bilara app, with the config in published being exclusively for consumption of external apps. Regardless, these configuration files should be editable whether they are in unpublished or published.
* The server also needs to react to config changes to _project.json, it generally does this automatically (via a webhook) when config files are changed on github but this webhook behaves differently when bilara itself makes updates so it has to be ensured that it reacts to changes made via bilara admin interface.

Bilara client needs a few modifications:

* Knowledge of whether the user is an admin or not.
* A link to the admin view (if they are an admin).
* A view which shows a list of editable config files.
* A view for editing those config files.
* And of course the GET and PUSH requests, probably via redux 

The editor view is proposed to be based on a javascript spreadsheet library, it can be simple, but:

* It should be possible to set fields to read only, to avoid accidentally modifying field names.
* If it has the ability to constrain values (like true/false or tickbox) or to pick from a list, that's a nice to have.
* The weight of the javascript isn't a huge issue, this is only for admins and we make certain assumptions about the hardware and network connection of bilara users anyway. So it can be lightweight but it doesn't really need to be as long as it works well.

**Comment by sujato** [comment]
With the new v2 files it's pretty  easy to view them as spreadsheet, so maybe that's good enough.

https://github.com/suttacentral/bilara-data/wiki/View-config-data-in-spreadsheet

It seems adding editing capability is too much work for too little result. I'll close this issue.
