### ISSUE TITLE
Question: Line by Line  Pali<->translation?

### ISSUE THREAD

**Issue by benlawraus** [suttacentral/bilara-data#1379]
Hi Bhante,
I'm wondering how pedantic should  index->translation?

For example:
```
  "dn21:1.12.67": "We venerate the Buddha, the victor, lord of men, ",
  "dn21:1.12.68": "who has crossed the flood and cut off doubt. ",

```
from (ms)
```
  "dn21:1.12.67": "Nitiṇṇaoghaṁ vicikicchachinnaṁ, ",
  "dn21:1.12.68": "Buddhaṁ namassāma jinaṁ janindaṁ. ",

```
Is bilara aiming for strict Pali<->translation line by line?
If so, these two lines should be swapped in the translation to match root Pali's index.

**Comment by sujato** [comment]
O hi Ben, how's it going?

The translations approximately map to the root, it is not one-to-one. This happens everywhere, but most acutely in verse, where it is often impossible and undesirable to translate strictly in sequence.

(FWIW, this is explained in the tools where you choose to view line by line: "the original text and translation are approximately matched line by line.")
