### ISSUE TITLE
Wrong boldfacing

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#1422]
pli-tv-bi-vb-ss4:2.1.17: remove boldface.

pli-tv-bi-vb-ss4:2.1.19: add boldface.

pli-tv-bi-vb-ss13:2.81-2-88: the word to be defined is not boldfaced, whereas the definition is. this needs to be reversed.

Thanks!

**Comment by sujato** [comment]
okay thanks, I finally got around to fixing this
