### ISSUE TITLE
Make segment numbers in dn29 agree with pts-cs

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#171]
This was a bug in the source. The pts-cs numbers were incorrect, they merely duplicated the sc numbers. I have corrected the pts-cs numbers in this commit.

https://github.com/suttacentral/bilara-data/commit/5b9a21bc913530def5a75241b23cb3e5abba32c0

We need to re-generate all the segment numbers for all files associated with this sutta.

Use the pts-cs numbers as basis.

Note that the pts-cs numbers are `x.1`. Don't forget to check if there are headings that require `x.0`!

**Comment by alple** [comment]
Fixed in https://github.com/suttacentral/bilara-data/commit/aa85616e3a560f048647fb719cf1649e82bd2786
