### ISSUE TITLE
Cross-validate references in bilara-data against ms_yuttadhammo

### ISSUE THREAD

**Issue by szymonzaczek** [suttacentral/bilara-data#174]
Validating whether references in bilara-data are in 100% agreement with ms_yuttadhamo.

Steps:

- extract ids/references from all html files
- sort ids/references from html files
- extract all ms references from bilara-data/reference
- sort ms ids currently in bilara-data/reference
- cross-validate references from both sources

**Comment by sujato** [comment]
This has been done.
