### ISSUE TITLE
More issues I am not allowed to fix

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#1791]
Thanks for sorting out all the other stuff. In fact, I have a backlog of other issues that need to be fixed. As much as I would like to do this myself, the system does not allow me. So here we go:

 •	pli-tv-bu-vb-ss8:4.2.0.2: “Impure but regarded as pure” > “Impure but viewed as pure”
•	pli-tv-bu-vb-ss8:4.3.0: “Pure but regarded as impure” > “Pure but viewed as impure” 
•	pli-tv-bu-vb-ss8:4.4.1.0: “Impure and regarded as impure” > “Impure and viewed as impure” 
•	pli-tv-bu-vb-ss8: 4.5.0: “Pure and regarded as pure” > “Pure and viewed as pure”
•	pli-tv-bu-vb-pc8: 1.1.0  + 1.2.26.0 + 2.1.0 + 2.1.9.0.1 + 2.1.9.0.2 + 2.2.0.1 + 2.2.0.2 + 2.2.13.0 + 2.3.0 + 2.3.55.0 +  2.4.0 + 2.5.0 + 2.6.0: remove “undefined” (the same problem occurs elsewhere, such as pj.1, pj.4, pc.1 – it seems to be everywhere!)
•	pli-tv-bu-vb-ss5:4.6.55.0: “Acting as a matchmaker for a man and one protected in various ways: any combination of motives” > “Acting as a matchmaker for a man and one protected in various ways: a single motive”
•	pli-tv-bu-vb-ss5:4.10.0: “Relationships arranged by various people: any combination of motives” > “Relationships arranged by various people: a single motive”
•	pli-tv-bu-vb-ss5:4.11.50.0: “The ones protected by various people taking the initiative: any combination of motives” > “The ones protected by various people taking the initiative: a single motive”
•	pli-tv-bu-vb-ss4:3.1.0.2: “Encouraging sexual intercourse to a single woman, etc.” > “Encouraging sexual intercourse to a single person or animal” 
•	pli-tv-bu-vb-ss3: “Referring to private parts” > “Referring to the private parts”; multiple times.
•	pli-tv-bu-vb-ss3:3.2.0.2: “Referring to private parts of a single woman, etc.” > “Referring to the private parts of a single person or animal”
•	pli-tv-bu-vb-ss2:3.1.0.3: “Making direct contact with a single woman, etc.: body to body” > “Making direct contact with a single person or animal: body to body” 
•	Ss2-ss4: “two beings of a different kind” > “two beings of different kinds” (multiple times)
•	pli-tv-bu-vb-pj4: delete the following segments: 4.5.8.2, 4.5.8.3, 4.5.8.4
•	pli-tv-bi-vb-np1: move horizontal rule between 2.1.20 and 2.1.21 to between 2.1.18 and 2.1.19.
•	pli-tv-kd7:1.5.1: move horizonal rule from after to before this segment.
•	pli-tv-kd17:4.1.7.3: “if they were rag-robe wearers for life, and whoever accepts a robe from a lay person would commit an offense;” > “if they were rag-robe wearers for life, and whoever accepts robe-cloth from a householder would commit an offense”;
•	pli-tv-kd14:14.33.41.2: change to: “‘If it seems appropriate to the Sangha, then for the benefit of these venerables and myself, I will confess in the midst of the Sangha both their and my own offenses by covering over as if with grass, except for heavy offenses and offenses connected with lay people. This is the motion.”
•	pli-tv-kd14:14.33.41.3: change to: “‘Any monk who approves of confessing our offenses in the midst of the Sangha by covering over as if with grass, except for heavy offenses and offenses connected with lay people, should remain silent. Any monk who does not approve should speak up.”
•	pli-tv-kd14:14.33.41.4: change to: “We have confessed our offenses in the midst of the Sangha by covering over as if with grass, except for heavy offenses and offenses connected with lay people. The Sangha approves and is therefore silent.”
•	pli-tv-bu-vb-pj4:4.5.63.2: “… “I obtain …” > “I obtain …”
•	pli-tv-bu-vb-pj4:4.5.63.3: “… “I master …” > “I master …”
•	pli-tv-kd12: 5.1.26.8 + 9.1.27.8: “He should not cancel the observance-day procedure of a regular monk.” > “He should not cancel the observance-day ceremony of a regular monk.”

**Comment by sujato** [comment]
ok, let me see

**Comment by sujato** [comment]
pli-tv-bu-vb-ss8:4.2.0.2: “Impure but regarded as pure” > “Impure but viewed as pure”
• pli-tv-bu-vb-ss8:4.3.0: “Pure but regarded as impure” > “Pure but viewed as impure”
• pli-tv-bu-vb-ss8:4.4.1.0: “Impure and regarded as impure” > “Impure and viewed as impure”
• pli-tv-bu-vb-ss8: 4.5.0: “Pure and regarded as pure” > “Pure and viewed as pure”

done

**Comment by sujato** [comment]
>pli-tv-bu-vb-pc8: 1.1.0 + 1.2.26.0 + 2.1.0 + 2.1.9.0.1 + 2.1.9.0.2 + 2.2.0.1 + 2.2.0.2 + 2.2.13.0 + 2.3.0 + 2.3.55.0 + 2.4.0 + 2.5.0 + 2.6.0: remove “undefined” (the same problem occurs elsewhere, such as pj.1, pj.4, pc.1 – it seems to be everywhere!)

I'm not sure what you're seeing here, but the word "undefined" doesn't occur anywhere in your translations. You're probably seeing something produced by a bug in the system. But I also can't see this on Bilara. Can you give a screenshot?

**Comment by sujato** [comment]
>pli-tv-bi-vb-np1: move horizontal rule between 2.1.20 and 2.1.21 to between 2.1.18 and 2.1.19.

This one is a bit complicated. The question is, should the instructions on sanghakamma be considered part of the defined term or not?

In Bu Np 21, the entire sequence of the sanghakamma is included in the definition list. You can see this visually (albeit subtly) because each line is indented. The list only ends at 3.40, before the cakka.

In Bi Np 1, on the other hand, the list ends before the `<hr>` appears.

Hmm. It seems to me that including such a long passage is stretching what a "definition list" is for. Also, it results in including `<article>` and `<p>` tags inside the list; this is allowable, but nested tags can sometimes behave unpredictably, so less nesting is better.

So I'd suggest ending the list before the sanghakamma, but include the sanghakamma within the padabhajaniya section. There's probably no need for the `<hr>` tag, as the end of the list is a sufficient visual cue.

```
"pli-tv-bi-vb-np1:2.1.0": "<section class='padabhajaniya'><h2>{}</h2>",
…
"pli-tv-bi-vb-np1:2.1.16": "<dd>{}</dd>",
  "pli-tv-bi-vb-np1:2.1.17": "<dt>{}</dt>",
  "pli-tv-bi-vb-np1:2.1.18": "<dd>{}</dd></dl>",
  "pli-tv-bi-vb-np1:2.1.19": "<p>{}",
  "pli-tv-bi-vb-np1:2.1.20": "{}</p>",
  "pli-tv-bi-vb-np1:2.1.21": "<p>{}</p>",
  "pli-tv-bi-vb-np1:2.1.22": "<article class='kamma'><p>{}</p></article>",
  "pli-tv-bi-vb-np1:2.1.23": "<p>{}",
  "pli-tv-bi-vb-np1:2.1.24": "{}",
…
  "pli-tv-bi-vb-np1:2.1.42": "{}</p>",
  "pli-tv-bi-vb-np1:2.1.43": "<article class='kamma'><p>{}</p></article></section>",
  "pli-tv-bi-vb-np1:2.2.0": "<section class='cakka'><h2>{}</h2>",
```

If you agree, I'll make sure this pattern is followed consistently in such cases.

**Comment by sujato** [comment]
I've made the rest of the changes. You can see the changed files here:

https://github.com/suttacentral/bilara-data/pull/1792/files

(This includes a lot of extra files where it's just that the trailing space has been fixed, ignore these.)

You should see these changes in Bilara right away, and on SC soon.

**Comment by brahmali** [comment]
> I'm not sure what you're seeing here, but the word "undefined" doesn't occur anywhere in your translations. You're probably seeing something produced by a bug in the system. But I also can't see this on Bilara. Can you give a screenshot?

Not sure what this is about. I think this has been on my list for a looong time and I can't remember anymore what it is about. Let's just leave it.

> If you agree, I'll make sure this pattern is followed consistently in such cases.

Sounds good! I am little bit concerned the separation ("the visual cue") will not be clear enough, but let's give it a go.

> "pli-tv-bu-vb-pj4:4.5.63.3": "“I master …” ",

You seem to have inadvertently introduced a quotation mark. It should look like this:

> "pli-tv-bu-vb-pj4:4.5.63.3": "“I master … ",

You seem to have missed this one (I have bolded the parts that need to be changed):

> pli-tv-kd14:14.33.41.3: change from: 
> "Any monk who approves of the confession in the midst of the Sangha **of both their and my own offenses** by covering over**,** as if with grass, except for heavy offenses and offenses connected with lay people, should remain silent. "
> to: 
> "‘Any monk who approves of **confessing our offenses** in the midst of the Sangha by covering over as if with grass, except for heavy offenses and offenses connected with lay people, should remain silent."

That seems to be it. Many, many, thanks! B

**Comment by sujato** [comment]
>let's give it a go

Sure. Once it's consistent, it's easy enough to change back. 

>inadvertently introduced a quotation mark.

oops, I'll fix this. It'll wait till I get back to Sydney later this week.

>pli-tv-kd14:14.33.41.3

This one seems to be correct already? perhaps you had a stale version in your browser?

**Comment by brahmali** [comment]
> This one seems to be correct already? perhaps you had a stale version in your browser?

You're right, it's good. Thanks for all of this!

**Comment by sujato** [comment]
Regarding the use of hr tags as separators following definition lists, I have decided to keep them for now. I have adjusted a couple of contexts, but kept changes minimal. Let's see what they look like: they are easier to remove than to add again. You can see the changes here.

https://github.com/suttacentral/bilara-data/pull/1811/files

Also, as for keeping long content inside a `<dd>` element, I have decided to keep this for now. Block-level elements are allowed, and while styling issues may happen, there are some contexts where it is clearly demanded.
