### ISSUE TITLE
Bilara i/o should replace existing content on import

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#190]
Currently Bilara i/o works additively on import. Thus in certain cases the segments that have been removed from the spreadsheet still appear. Eg.:

Export:
1.1: It seems a horse
1.2: is not a duck.
1.3: But a house is still a house.

merge 1.1 and 1.2 in spreadsheet:

1.1: It seems a horse is not a duck.
1.2: But a house is still a house.

On export we have:

1.1: It seems a horse is not a duck.
1.2: But a house is still a house.
1.3: But a house is still a house.

The details of this don't matter, the point is that there must be 100% confidence that the JSON files are identical to the spreadsheet.

**The import must delete the old JSON files and import exactly what is in the spreadsheet**.

**Comment by jhanarato** [comment]
Hey Bhante,

You asked me to have a look at this. Might take a while.

**Comment by sujato** [comment]
This has been fixed
