### ISSUE TITLE
Kd.12, numbers not matching up

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#1911]
Segment 1.4.29 says there are 94 kinds of proper conduct, but the list just before ends at item 62. The reason for this is that segments 1.4.12 to 1.4.15 are  contractions, wherein 9 actual items are shown in a single segment. If you expand it all, you get exactly 94 items in the list. Is there anything we can do to get the last item to show 94 rather than 62?

**Comment by sujato** [comment]
Thanks for noticing, actually this is an issue with the styling, the markup to handle numbers correctly was already present. I hope it is fixed now!

I have also made sure that this is handled correctly in the LaTeX conversion:

https://github.com/suttacentral/publications/issues/127
