### ISSUE TITLE
Kd.2, Kd.4, and Kd.12 changes, please!

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#1923]
Remove horizontal rule after the following segments:

> Kd.2: 22.4.3, 22.4.8, 27.7.7, 27.8.7
> Kd.4: 3.5.46, 3.5.74, 16.16.2, 16.20.8, 16.23.7, 16.24.7, 16.25.7, 17.2.5, 17.3.4, 18.4.9, 18.5.7
> Kd.12: 1.1.30, 4.1.29, 5.1.22, 6.1.29, 9.1.23

Add horizontal rule after:

> Kd.2: 27.9.7

Missing html in Kd.12:

> 9.1.74 `<p class='end'>{}</p>`
> 9.1.75 `<p class='endsutta'>{}</p>`
> 9.1.76 `<p class='end'>{}</p>`

**Comment by sujato** [comment]
>Add horizontal rule after:
>    Kd.2: 27.9.7

?? this seems wrong.

Others are fixed.

**Comment by brahmali** [comment]
> ?? this seems wrong.

Yeah, it's a bit marginal. Might as well leave it out.

Otherwise, sādhu!
