### ISSUE TITLE
Issues, issues, and more issues!

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#1963]
**Remove hr after the following segments:**

**Kd.1**: 6.6.5 + 6.9.6 + 20.6.3 + 20.9.7 + 20.11.6 + 20.14.9 + 20.19.5 + 20.21.5 + 25.11.8 + 25.14.2 + 25.19.8 + 25.22.4 + 26.4.8 + 26.6.8 + 26.7.42 + 26.10.4 + 27.2.6 + 28.6.8 + 29.4.10 + 32.3.27 + 32.3.42 + 32.3.84 + 32.3.99 + 33.1.30 + 33.1.42 + 33.1.84 + 33.1.99 + 34.1.11 + 54.4.1 + 76.1.16 + 76.3.9

**Kd.2**: 6.2.7 + 7.1.8 + 8.2.10 + 9.2.15 + 12.2.11 + 14.1.4 + 15.1.14 + 15.4.8 + 15.7.10 + 15.10.10 + 18.4.4 + 22.4.3 + 22.4.8 + 23.3.26 + 23.3.31 + 27.7.7 + 35.3.3

**Kd.3**: 5.12.43 + 6.5.5 + 6.9.5 + 6.15.5 + 6.18.5 + 6.23.5 + 6.26.5 + 7.8.4 + 9.2.8 + 11.2.6 + 11.5.11 + 11.7.10 + 11.11.10.

**Kd.5**: 8.3.9

**Kd.8**: 1.5.6 + 1.35.10 + 2.1.10 + 5.2.12 + 7.2.11 + 8.1.15 + 9.1.19 + 13.6.8 + 19.1.7 + 20.2.10 + 21.1.13 + 21.1.16 + 25.5.4 + 27.2.21 + 27.4.1

**Kd.9**: 1.6.6 + 3.4.10 + 3.5.8 + 3.6.4 + 3.7.8 + 3.8.4 + 4.9.9 + 6.3.17 + 6.6.15

**Kd.10**: 2.20.15 + 5.5.20 + 5.6.40 + 5.7.9 + 5.8.9 + 6.1.6

**Add hr after following segments:**

**Kd.6**: 13.2.29

**Remove paragraph after the following segments:**

**Kd.9**: 6.3.1 + 6.4.18 + 6.6.1 + 6.8.1

**Kd.10**: 5.6.19 + 5.6.30 

**Add paragraph after the following segments:**

**Kd.9**: 3.3.3 + 3.5.1 + 3.6.1 + 3.7.1 + 3.8.1 + 3.9.1 + 4.9.4 + 4.10.2

Bhikkhu NP2: after “Permutations” heading add another heading: “Permutations part 1” + before segment 3.18.1 add heading “Permutations part 2”

Bhikkhu-pāc. 36: segment 2.1.12: comment intrudes in the translation.

**Comment by sujato** [comment]
Oky doky, will get to these soon.

Meanwhile, I just found another little quirkette. It seems that in your translations, you’ve been using the wrong character for ’. Latex is complaining that the character is missing from the font, and just shows an empty box.

You’ve been using ʼ, which is U+02BC:

https://unicode-table.com/en/search/?q=%CA%BC

You're also using ʻ instead of ‘

I’ll make a bulk change to your texts, so you don’t have to do anything. Just make sure to use the right character going forward.

Oh, and here's a PDF of the Vinaya, vol 1. Mostly it's looking pretty good!

[Theravāda-Collection-on-Monastic-Law-brahmali-2022-09-07-1.pdf](https://github.com/suttacentral/bilara-data/files/9533029/Theravada-Collection-on-Monastic-Law-brahmali-2022-09-07-1.pdf)

**Comment by brahmali** [comment]
Okay. I've tried to use the following, which I thought were correct: ʻ and ʼ. How do I know if these are actually correct or not?

And wow, it's amazing what you've done! Thank you so much for all the careful and hard work that lies behind this. I don't think there are words to sufficiently express my awe! All I can say is that it's extraordinarily gratifying to have one's own translation laid out in such a beautiful way. You are the best! Like, the very best.

Please allow me to sit on this for a while. I would like to consider it properly. At the same time I will have to write the preface and the acknowledgments page. And perhaps other intros, as you have suggested earlier.

On a related matter, I am a little bit desperate to have the fist ten chapters of the Khandhakas published on SuttaCentral. I need to cut and paste for the Thai project, which unfortunately has occupied a bit too much of my time recently. If this could happen within a day or two, I would be most grateful.

Sādhooo!!!

**Comment by sujato** [comment]
>How do I know if these are actually correct or not?

I mean, it should be just the ordinary characters used by any autocorrect. But to test, just paste it into any unicode lookup, such as the one I linked above.

>I don't think there are words to sufficiently express my awe! 

😊

>the fist ten chapters of the Khandhakas published on SuttaCentral

Sorry, I don't understand: are these not already published? I though the whole thing was there.

***

 25.5.4 ??? doesn't exist.

paragraph after Kd.10: 5.6.19, I think you mean 5.6.18

I've done the hr and p fixes, will get to others soon.

**Comment by sujato** [comment]
>Bhikkhu NP2: after “Permutations” heading add another heading: “Permutations part 1” + before segment 3.18.1 add heading “Permutations part 2”

Are you sure? This seems excessive. The added headings don't give any information except that "this is a different part of the section", and that is precisely what the `<hr>` is for.

>Bhikkhu-pāc. 36: segment 2.1.12: comment intrudes in the translation.

Yikes, fixed.

**Comment by brahmali** [comment]
> Sorry, I don't understand: are these not already published? I though the whole thing was there.

I just meant an update. But no worries; it's all been sorted.

> 25.5.4 ??? doesn't exist.

Sorry, should be Kd.8:24.5.4

> I think you mean 5.6.18

Ya!

> Are you sure? This seems excessive. 

Looking at it again, I am happy to drop it. It's been sitting on my to do list for a long time. I can't really recall why I wanted the change.

Thanks for all of this! There will be more changes coming up quite soon. Sorry.
