### ISSUE TITLE
Move blurb to SN 24.1 to correct place and number it correctly

### ISSUE THREAD

**Issue by sabbamitta** [suttacentral/bilara-data#1998]
See screenshot:
![Screenshot from 2022-10-01 12-46-50](https://user-images.githubusercontent.com/43345786/194156313-0640794e-5ba6-4c64-b802-a55f1721e907.png)

https://bilara.suttacentral.net/translation/sn-blurbs_translation-de

**Comment by sujato** [comment]
Fixed with this pr:

https://github.com/suttacentral/bilara-data/pull/1999
