### ISSUE TITLE
/acknowledgments page updates

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/bilara-data#2095]
Wondering if you need to rethink this page or if you will just add in new segments as new things get added.

I tried to remove the present tense from all of these pghs.

>However we decided to go beyond just making some additions, and have embarked on a complete redesign.
>However we decided to go beyond just making some additions, and embarked on a complete redesign.

>While the data structure has been retained with only incremental improvements, the entire code for the website has been rewritten.
>While the data structure **was** retained with only incremental improvements, the entire code for the website **was** been rewritten.

>For this new edition, the main team is as follows.
>For this edition, the main team was as follows.

Here I'll just put the rewrite:
>While the 2012 rebuild served us well, we saw the need for a systematic upgrade. We had made a series of incremental changes, each one of which was added to the original structure somehow, and things got a bit creaky after a while. At a certain point it’s better to rebuild in a cleaner and more systematic way. We embarked on this process in 2017. Key underlying changes included internationalization; integration of Sutta, Vinaya, and verse parallels; and the addition of segmented translations. The core development team for this process was as follows.

This paragraph seems kind of time sensitive, no?
>In order to enable donations through the site, we set up a non-profit charity. This is incorporated in Australia, and manages the finances for SuttaCentral. Special thanks to Deepika Weerakoon, who set it up and acts as Financial Officer. Trustees are Bhante Sujato, Bhante Brahmali, and John Kelly.

How about
>The Sutta Central Development trust is a non-profit charity incorporated in Australia to manage finances for Sutta Central. Special thanks to Deepika Weerakoon, who set it up.

Then perhaps some language that points people to some other place to learn how to donate and find out who the people involved are?

What do you want to do with the last section? It's alphabetical, so it's hard to add people in and maintain segments. 

>Our volunteers and helpers

Not sure how helpers and volunteers differ? Are helpers paid?

>In addition, we express our grateful thanks to the following. SuttaCentral exists to draw together the diverse strands of the early Buddhist tradition, and we can only do this through the help of many people. This list is very incomplete, so please let us know if we missed anyone out.

to

>SuttaCentral exists to draw together the diverse strands of the early Buddhist tradition, and we can only do this through the help of many people, some of whom are listed below. We express our heartfelt thanks to all who have made this possible. This list is very incomplete, so please let us know if we missed anyone.

I was conservative with my changes not knowing how drastic you wanted to be.

**Comment by sujato** [comment]
I'd definitely like to have more attention to adding new names on here, a lot of folks are missing! But for now we can just bring it up to date.

Your proposed changes sound reasonable!

Why not go ahead and make the changes and we'll see how it goes.

**Comment by ccronje** [comment]
Bhante @sujato, will Nilushi's work on biographies be included here?

**Comment by thesunshade** [comment]
I'm not closing this issue since it sounds like there are people that need to be added. But I believe I have made all the changes proposed.

**Comment by thesunshade** [comment]
I'm going to close this as it looks like it is done.
