### ISSUE TITLE
/home page updates

### ISSUE THREAD

**Issue by thesunshade** [suttacentral/bilara-data#2097]
# Top three cards
> The Abhidhamma (spelled abhidharma in Sanskrit) is intended for advanced students who have mastered the teachings of the discourses.

>The Abhidhamma (Sanskrit: abhidharma) is intended for advanced students who have mastered the teachings of the discourses.

Personally I agree about the A. being for advanced students (if it's for anyone) but I'm not sure that is a neutral view. Or if being neutral even matters.

Essay titles: Should they be in title case? Would this make it more clear what they are? Maybe it doesn't matter.

# Video text
>Many of these scriptures have now been translated into the world’s languages.
>Many of these scriptures have now been translated into the modern languages of the world.

??? Generally the rule is to use the "of" possessive for inanimate things. But maybe the world in this case is animate? "Of" just sounds better to me.

# What's here
>This is a large collection of teachings attributed to the Buddha or his earliest disciples, who were teaching in India around 2500 years ago.
>This large collection of teachings is attributed to the Buddha and his earliest disciples, who taught in India around 2500 years ago.

Something feels odd about "around". I wonder if it could be dropped and still give the same meaning. 

# Where to begin
>There are thousands of early Buddhist texts, and they’re not organized for easy reading. But here’s the good news: you are not alone. We’ve been down this road ourselves, and have tried to make it a little easier for you. Here are some things you can try.
>The thousands of early Buddhist texts are not always easy to approach as a beginner. But here’s the good news: you are not alone. We’ve been down this road ourselves, and have tried to make it easier for you. Here are some things you can try.

Something about "not organized for easy reading" doesn't ring true or really convey anything to new comers. It also implies that the texts are disorganized, which to me they are not. ¯\\\_(ツ)_/¯

# Related projects

The link to more awesome things should go directly to the readme: 
https://github.com/suttacentral/awesome#readme 
This reduces some of the wonkiness in linking to repositories. Would it even be possible to turn this into a github pages thing so it looked like a real site?

>Voice makes SuttaCentral’s texts and translations accessible to the visually impaired and the sighted. 
>SuttaCentral Voice makes our texts and translations accessible to the visually impaired as well as the sighted. 

To the outsider it's not clear that "Voice" is a service not a noun.

> * Find Suttas on Voice.
I expected that text to be linked up.

> Built from the ground up by SuttaCentral, Bilara is a web interface for Sutta translation. Our team is using it to create new translations of Suttas in the world’s languages.
> Bilara is software built by SuttaCentral to assist sutta translation. Our team is using it to create new translations of Suttas in the languages of the world.

Again, the "of" thing.

# A Reader's guide
>The suttas of the Pali Canon (Tipiṭaka), especially the four main nikāyas, are essential reading for anyone who wishes to understand the Buddha and his teaching. Bhikkhu Sujato has prepared an extensive set of reading guides for the serious student. These provide essential background and survey most of the core teachings from the perspective of early Buddhism.
>The Pali suttas, especially the four main books, are essential reading for anyone who wishes to understand the Buddha and his teaching. Bhikkhu Sujato has prepared an extensive set of reading guides for the serious student. These provide essential background and explain the core teachings of early Buddhism.

Are they really only for the serious student?

# Indexes

>Like any specialized field, Buddhist studies has it's own terminology and content. It's easy to get lost or to miss references, so here we provide indexes of terms in the early texts sorted by subject, name and simile, as well a glossary of important terms. These hand-curated lists offer another way to find the sutta or passage that you're looking for.
>Here we provide indexes of terms in the early texts sorted by subject, name, and simile, as well a glossary of important terms. If using the site search is not successful, these hand-curated lists offer a way to find the sutta or passage that you're looking for.

The first part didn't seem necessary. I also mentioned site search since it wasn't clear what the "another way" was in opposition to. Plus, it never hurts to remind people about the site search.

# Footer

Source code on Github links to 
https://github.com/suttacentral/suttacentral. 
Should it just link to 
https://github.com/suttacentral
?

**Comment by sujato** [comment]
Yes, all good suggestions.

- I'm happy to leave "world's languages"
- Are they really only for the serious student? sure, take that bit out.
