### ISSUE TITLE
Fix numbering in SN blurbs

### ISSUE THREAD

**Issue by sabbamitta** [suttacentral/bilara-data#2101]
The blurb for SN 29.1 is numbered sn28.159 in Bilara. https://bilara.suttacentral.net/translation/sn-blurbs_translation-de resp. [bilara-data/sn-blurbs_root-en.json at unpublished · suttacentral/bilara-data · GitHub](https://github.com/suttacentral/bilara-data/blob/unpublished/root/en/blurb/sn-blurbs_root-en.json).

Number should be `sn29.1` instead.

**Comment by sujato** [comment]
thx, fixed.
