### ISSUE TITLE
More Khandhaka corrections

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#2236]
**Remove paragraph after the following segments:** 

**Kd.1**: 25.7.1 + 32.2.1 + 76.3.5
**Kd.11**: 16.1.12, 18.1.6
**Kd.12**: 1.1.30 + 4.1.29 + 5.1.22 + 6.1.29 + 9.1.23
**Kd.13**: 2.2.1 + 3.2.1 + 4.2.1 + 5.2.1 + 6.1.10 + 7.2.1 + 8.2.1 + 9.2.1 + 10.1.8 + 10.1.24 + 12.2.1 + 13.1.7 + 14.2.1 + 14.3.1 + 16.1.7 + 19.1.7 + 20.2.1 + 21.1.9 + 22.3.2 + 24.3.2 + 26.2.1
**Kd.14**: 4.1.10 + 4.4.35 + 4.10.2 + 5.2.1 + 14.27.12 + 14.28.19
**Kd.15**: 24.2.3 + 24.3.3 + 24.3.27 + 34.1.12
**Kd.16**: 4.3.19 + 4.6.2 + 8.5 + 11.2.6
**Kd.17**: 1.1.11 + 1.4.29 + 2.2.13 + 2.3.2 + 3.5.2 + 3.10.15 + 4.2.6 + 4.7.2
**Kd.18**: 4.5.24 + 5.1.15

**Add paragraph after the following segments:**

**Kd.12**: 1.1.29 + 4.1.28 + 5.1.21 + 6.1.28 + 9.1.22
**Kd.14**: 14.27.11 + 14.28.18
**Kd.15**: 34.2.3
**Kd.16**: 3.7.15 + 6.1.4 + 6.1.6 + 7.5 + 7.7
**Kd.17**: 4.7.33
**Kd.18**: 6.2.1

**Remove hr after following segments:**

**Kd.12**: 1.1.30 + 4.1.29 + 5.1.22 + 6.1.29 + 9.1.23
**Kd.13**: 26.3.13
**Kd.14**: 2.1.9 + 2.1.18 + 3.1.9 + 3.1.18 + 4.5.13 + 4.6.14 + 4.10.31 + 5.2.61 + 6.2.1 + 8.2.1 + 11.2.15 + 12.3.2.3 + 12.3.2.6 + 12.3.2.9 + 13.2.16 + 13.3.14 + 13.3.28 + 14.2.16 + 14.7.3 + 14.8.20 + 14.9.17 + 14.10.8 + 14.11.14 + 14.12.16 + 14.13.15 + 14.14.13 + 14.21.6 + 14.22.12
**Kd.15**: 18.1.14 + 20.3.2 + 20.3.4 + 20.6.2 + 20.6.4 + 27.5.25
**Kd.16**: 1.5.24 + 2.1.25 + 2.2.4 + 2.2.14 + 2.3.16 + 3.1.11 + 3.4.5 + 11.2.16
**Kd.17**: 1.3.53 + 1.4.34 + 3.1.16 + 3.2.23 + 3.3.23 + 3.10.18 + 3.13.21 + 3.16.19 + 4.1.14 + 4.1.25 + 4.3.14 + 5.3.22 + 5.4.16 + 5.5.4 + 5.5.54
**Kd.18**: 5.2.44+ 11.5.9 + 11.8.2 + 11.13.8 + 11.16.4 + 12.5.8 + 12.7.6 + 12.8.3 + 12.10.4 + 12.11.48 + 12.11.63 + 12.11.105 + 12.11.120 + 12.11.182 + 12.11.194 + 12.11.200 + 12.11.215

**Add hr after following segments:**

**Kd.17**: 2.4.46

**Other:**

**Kd.14**: Add semi-bold to the following segments: 14.33.18-14.33.21 + 14.33.23-14.33.26
**Kd.15**: Add bold to segments: 14.4.7 
**Kd.16**: Remove bold from segments (remove from rule class): 3.7.16
Add bold to segments: 11.4.4 + 11.4.5 + 11.4.6 + 11.4.7 + 11.4.8

**Comment by sujato** [comment]
**Remove paragraph after the following segments:** 


- [x] kd1:25.7.1
- [x] kd1:32.2.1
- [x] kd1:76.3.5
- [x] kd11:16.1.12
- [x] kd11:18.1.6
- [x] kd12:1.1.30
- [x] kd12:4.1.29
- [x] kd12:5.1.22
- [x] kd12:6.1.29
- [x] kd12:9.1.23
- [x] kd13:2.2.1
- [x] kd13:3.2.1
- [x] kd13:4.2.1
- [x] kd13:5.2.1
- [x] kd13:6.1.10
- [x] kd13:7.2.1
- [x] kd13:8.2.1
- [x] kd13:9.2.1
- [x] kd13:10.1.8
- [x] kd13:10.1.24
- [x] kd13:12.2.1
- [x] kd13:13.1.7
- [x] kd13:14.2.1
- [x] kd13:14.3.1
- [x] kd13:16.1.7
- [x] kd13:19.1.7
- [x] kd13:20.2.1
- [x] kd13:21.1.9
- [x] kd13:22.3.2
- [x] kd13:24.3.2
- [x] kd13:26.2.1
- [x] kd14:4.1.10
- [x] kd14:4.4.35
- [x] kd14:4.10.2
- [x] kd14:5.2.1
- [x] kd14:14.27.12
- [x] kd14:14.28.19
- [x] kd15:24.2.3
- [x] kd15:24.3.3
- [x] kd15:24.3.27
- [x] kd15:34.1.12
- [ ] kd16:4.3.19
- [x] kd16:4.6.2
- [x] kd16:4.8.5
- [x] kd16:11.2.6
- [x] kd17:1.1.11
- [x] kd17:1.4.29
- [ ] kd17:2.2.13
- [x] kd17:2.3.2
- [x] kd17:3.5.2
- [x] kd17:3.10.15
- [x] kd17:4.2.6
- [x] kd17:4.7.2
- [x] kd18:4.5.24
- [x] kd18:5.1.15


**Add paragraph after the following segments:**


- [x] kd12:1.1.29
- [x] kd12:4.1.28
- [x] kd12:5.1.21
- [x] kd12:6.1.28
- [x] kd12:9.1.22
- [x] kd14:14.27.11
- [x] kd14:14.28.18
- [x] kd15:34.2.3
- [x] kd16:3.7.15
- [x] kd16:6.1.4
- [x] kd16:6.1.6
- [ ] kd16:6.7.5
- [ ] kd16:6.7.7
- [x] kd17:4.7.33
- [x] kd18:6.2.1


**Remove hr after following segments:**


- [ ] kd12:1.1.30
- [ ] kd12:4.1.29
- [ ] kd12:5.1.22
- [ ] kd12:6.1.29
- [ ] kd12:9.1.23
- [x] kd13:26.3.13
- [x] kd14:2.1.9
- [x] kd14:2.1.18
- [x] kd14:3.1.9
- [x] kd14:3.1.18
- [x] kd14:4.5.13
- [x] kd14:5.2.61
- [x] kd14:4.6.14
- [x] kd14:4.10.31
- [x] kd14:6.2.1
- [x] kd14:8.2.1
- [x] kd14:11.2.15
- [x] kd14:12.3.2.3
- [x] kd14:12.3.2.6
- [x] kd14:12.3.2.9
- [x] kd14:13.2.16
- [x] kd14:13.3.14
- [x] kd14:13.3.28
- [x] kd14:14.2.16
- [x] kd14:14.7.3
- [x] kd14:14.8.20
- [x] kd14:14.9.17
- [x] kd14:14.10.8
- [x] kd14:14.11.14
- [x] kd14:14.12.16
- [x] kd14:14.13.15
- [x] kd14:14.14.13
- [x] kd14:14.21.6
- [x] kd14:14.22.12
- [x] kd15:18.1.14
- [x] kd15:20.3.2
- [x] kd15:20.3.4
- [x] kd15:20.6.2
- [x] kd15:20.6.4
- [x] kd15:27.5.25
- [x] kd16:1.5.24
- [x] kd16:2.1.25
- [x] kd16:2.2.4
- [x] kd16:2.2.14
- [x] kd16:2.3.16
- [x] kd16:3.1.11
- [x] kd16:3.4.5
- [x] kd16:11.2.16
- [x] kd17:1.3.53
- [x] kd17:1.4.34
- [x] kd17:3.1.16
- [x] kd17:3.2.23
- [x] kd17:3.3.23
- [x] kd17:3.10.18
- [x] kd17:3.13.21
- [x] kd17:3.16.19
- [x] kd17:4.1.14
- [x] kd17:4.1.25
- [x] kd17:4.3.14
- [x] kd17:5.3.22
- [x] kd17:5.4.16
- [x] kd17:5.5.4
- [x] kd17:5.5.54
- [x] kd18:5.2.44
- [x] kd18:11.5.9
- [x] kd18:11.8.2
- [x] kd18:11.13.8
- [x] kd18:11.16.4
- [x] kd18:12.5.8
- [x] kd18:12.7.6
- [x] kd18:12.8.3
- [x] kd18:12.10.4
- [x] kd18:12.11.48
- [x] kd18:12.11.63
- [x] kd18:12.11.105
- [x] kd18:12.11.120
- [x] kd18:12.11.182
- [x] kd18:12.11.194
- [x] kd18:12.11.200
- [x] kd18:12.11.215


**Add hr after following segments:**


- [x] kd17:2.4.46

**Comment by brahmali** [comment]
**Remove paragraph after the following segments:**

- [x] kd16:4.3.19: remove `</p>` and also remove `<p>` at kd16:4.3.28. Also the html from 
- [x] kd16:4.3.20-4.3.27 is defunct, that is, the verses have been removed.

kd16:4.8.5: my mistake. (I've checked it off.)

- [x] kd17:2.2.13: the problem is the `</p>` at segment 2.2.24 (and the `<p>` at 2.2.25). The `</p>` at 2.2.26 is correct.

**Add paragraph after the following segments:**

- [x] kd16:6.7.5 > kd16:7.5
- [x] kd16:6.7.7 > kd16:7.7

**Remove hr after following segments:** > **Remove _paragraph_ after following segments:** 

 - [x] kd12:1.1.30
 - [x] kd12:4.1.29
 - [x]  kd12:5.1.22
 - [x]  kd12:6.1.29
 - [x]  kd12:9.1.23

**Comment by sujato** [comment]
remainder are non-issues.
