### ISSUE TITLE
More Vinaya corrections

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#2361]
**Kd.19:** 
**remove hr after:** 2.1.11 + 3.4.11 + 3.5.11 + 3.7.8 + 3.8.11 + 3.9.11 + 5.3.10 + 5.5.10 + 5.6.7
**remove paragraph after the following segments:** 1.1.10 + 5.5.8

**Kd.20:** 
**remove hr after:** 16.2.23 + 17.1.11 + 17.2.4 + 17.2.17 + 17.5.12 + 17.7.25 + 17.8.38 + 22.3.44 + 27.4.14;
**remove paragraph after the following segments:** 17.2.13;
**add headings after the following segments:** 16.2.23 (“The ordination ceremony”) + 19.3.8 (“Mutual authority between monks and nuns”) + 20.1.46 (“Vehicles”) + 21.1.17 (“Ordination by messenger”) + 22.3.46 (“Various regulations for nuns”)

**Kd.21:** 
**remove hr after:** 1.4.14 + 1.7.14 + 1.7.21 + 1.7.28 + 1.7.37 + 1.8.12 + 1.9.43 + 1.12.13 + 1.14.33;
**add headings after the following segments:** 1.4.14 (“The communal recitation at Rājagaha”);

**Kd.22:**
**remove hr after:** 1.1.14 + 1.2.11 + 1.3.43 + 1.4.42 + 1.6.6 + 1.7.10 + 1.9.3 + 1.9.44 + 1.10.14 + 1.10.15 + 1.10.19 + 1.10.23 + 1.10.27 + 1.10.32 + 1.10.36 + 1.10.40 + 1.10.44 + 1.10.46 + 2.4.7 + 2.5.13 + 2.6.19 + 2.7.23 + 2.7.33;
**remove paragraph after segment:** 1.2.7 + 2.3.24 + 2.6.1 + 2.7.31
**add headings after the following segments:** 1.2.11 (“Why monastics should not accept gold, silver, or money”) + 1.7.10 (“Yasa gathers supporters”) + 1.9.44 (“The ten practices explained”) + 1.10.55 (“Both sides gathering supporters”) + 2.6.19 (“Choosing a committee”) + 2.7.32 (“The committee decides on the ten practices”);

**Remove hr after:**
**Pr.1:** 8.2.3 + 8.2.125 + 9.3.27 + 9.3.49 + 9.3.67 + 9.4.26 + 9.4.56 + 9.4.69 + 9.5.18 + 9.6.26;
**Pr.2:** 4.2.8 + 4.6.7 + 4.7.8 + 4.8.8 + 4.10.8. + 4.11.6 + 4.12.8 + 4.13.8 + 4.15.8 + 4.16.5 + 4.19.5 + 4.21.7 + 4.22.5 + 4.24.5 + 4.25.5 + 4.26.5;
**Pr.3:** 4.2.6 + 4.2.25 + 4.2.34 + 4.3.8 + 4.4.20 + 4.8.4 + 4.9.42;
**Pc.4:** 2.1.16; 
**Pc.28:** 3.1.10 + 3.1.13;

**Add hr after:** 
**Pr.4:** 8.9.12; 
**Np.1:** 4.18; 
**Np.10:** 2.2.3 + 2.2.11; 
**Np21:** 3.58; 
**Np.27:** 2.27 (+ remove indentation after hr); 
**Np.24:** 2.9; 

**Move hr:** 
**Np21:** from after 3.14 to after 3.13; 

**Indent paragraph at:** 
**Pr.1:**  from 8.2.4 to 8.4.21; 
**Pr.2:** 4.2.9 + 4.2.12 + 4.2.17 + 4.6.8 + 4.7.9 + 4.8.9 + 4.10.9 + 4.10.12 + 4.11.7 + 4.12.9 + 4.12.12 + 4.12.17 + 4.13.9 + 4.13.14 + 4.15.9 + 4.16.6 + 4.16.9 + 4.19.6 + 4.19.8 + 4.21.8 + 4.21.9 + 4.22.6 + 4.24.6 + 4.25.6 + 4.26.6; 
**Pr.3:** 4.2.7 + 4.2.9 + 4.2.11 + 4.2.26 + 4.2.29 + 4.2.32; 

**Add paragraph after:** 
**Pr.1:** 8.2.4 + 8.3.1 + 8.4.1; 

**Remove bold:** 
**Sg.13:** 2.22; 

**Remove bold-face:** 
**Np.1:** 4.11-14; 
**Np.21:** 3.51-54; 
**Np.28:** 2.33-36; 

**Other**: 
**Sg.9:** second bullet point should be merged with the first one (it’s not a separate pretext).

**Comment by sujato** [comment]
**remove hr after**
 
 - [x] kd19:2.1.11
 - [x] kd19:3.4.11
 - [x] kd19:3.5.11
 - [x] kd19:3.7.8
 - [x] kd19:3.8.11
 - [x] kd19:3.9.11
 - [x] kd19:5.3.10
 - [x] kd19:5.5.10
 - [x] kd19:5.6.7
 - [x] kd20:16.2.23
 - [x] kd20:17.1.11
 - [x] kd20:17.2.4
 - [x] kd20:17.2.17
 - [x] kd20:17.5.12
 - [x] kd20:17.7.25
 - [x] kd20:17.8.38
 - [x] kd20:22.3.44
 - [x] kd20:27.4.14
 - [x] kd21:1.4.14
 - [x] kd21:1.7.14
 - [x] kd21:1.7.21
 - [x] kd21:1.7.28
 - [x] kd21:1.7.37
 - [x] kd21:1.8.12
 - [x] kd21:1.9.43
 - [x] kd21:1.12.13
 - [x] kd21:1.14.33
 - [x] kd22:1.1.14
 - [x] kd22:1.2.11
 - [x] kd22:1.3.43
 - [x] kd22:1.4.42
 - [x] kd22:1.6.6
 - [x] kd22:1.7.10
 - [x] kd22:1.9.3
 - [x] kd22:1.9.44
 - [x] kd22:1.10.14
 - [x] kd22:1.10.15
 - [x] kd22:1.10.19
 - [x] kd22:1.10.23
 - [x] kd22:1.10.27
 - [x] kd22:1.10.32
 - [x] kd22:1.10.36
 - [x] kd22:1.10.40
 - [x] kd22:1.10.44
 - [x] kd22:1.10.46
 - [x] kd22:2.4.7
 - [x] kd22:2.5.13
 - [x] kd22:2.6.19
 - [x] kd22:2.7.23
 - [x] kd22:2.7.33
 - [x] pj1:8.2.3
 - [x] pj1:8.2.125
 - [x] pj1:9.3.27
 - [x] pj1:9.3.49
 - [x] pj1:9.3.67
 - [x] pj1:9.4.26
 - [x] pj1:9.4.56
 - [x] pj1:9.4.69
 - [x] pj1:9.5.18
 - [x] pj1:9.6.26
 - [x] pj2:4.2.8
 - [x] pj2:4.6.7
 - [x] pj2:4.7.8
 - [x] pj2:4.8.8
 - [x] pj2:4.10.8.
 - [x] pj2:4.11.6
 - [x] pj2:4.12.8
 - [x] pj2:4.13.8
 - [x] pj2:4.15.8
 - [x] pj2:4.16.5
 - [x] pj2:4.19.5
 - [x] pj2:4.21.7
 - [x] pj2:4.22.5
 - [x] pj2:4.24.5
 - [x] pj2:4.25.5
 - [x] pj2:4.26.5
 - [x] pj3:4.2.6
 - [x] pj3:4.2.25
 - [x] pj3:4.2.34
 - [x] pj3:4.3.8
 - [x] pj3:4.4.20
 - [x] pj3:4.8.4
 - [x] pj3:4.9.42
 - [x] pj4:2.1.16 
 - [x] pc28:3.1.10
 - [x] pc28:3.1.13
 
 **add hr after** 

 - [x] pj4:8.9.12 
 - [x] np1:4.18 
 - [x] np10:2.2.3
 - [x] np10:2.2.11 
 - [x] np21:3.58 
 - [x] np27: 2.27 (+ remove indentation after hr) 
 

 **remove paragraph after**
 
 - [x] kd19:1.1.10
 - [x] kd19:5.5.8
 - [x] kd20:17.2.13
 - [x] kd22:1.2.7
 - [x] kd22:2.3.24
 - [x] kd22:2.6.1
 - [x] kd22:2.7.31
 
 **add paragraph after** 
 
 - [x] pj1:8.2.4
 - [x] pj1:8.3.1
 - [x] pj1:8.4.1 
 
 
 
 **remove bold**
 
 - [x] ss13:2.22
 - [x] np1:4.11-14 
 - [x] np21:3.51-54 
 - [x] np28:2.33-36 
 
 **other**

 - [x] ss9 second bullet point should be merged with the first one (it’s not a separate pretext).

**Comment by sujato** [comment]
In the four "remove bold" cases, the first was a definition marked as a term, in the remaining three they were `class='rule'`.

**Comment by brahmali** [comment]
**add hr after**

- [x] np24:2.9: yes, please add this one. This follows the pattern elsewhere. I may go through the Vibhangas once more to reduce the usage of hr's, but this is not the right time.

**move hr**

- [x] np21:3.14 to after 3.13: yes, this too needs to be done. Segment 3.14 then needs to be merged with the following paragraph, that is, removing the `</p>`. Again, this is for consistency.

**Comment by sujato** [comment]
**indent paragraph** 
 
 - [x] pj1:8.2.4 to 8.4.21  (This just means making it part of the gloss, which you have done I think.)
 - [x] pj2:4.2.9  (This, and the rest of Bu Pj 2 and also Pj 3, concern making the segment part of the preceding gloss while leaving the paragraph distinction intact.)
 - [x] pj2:4.2.12
 - [x] pj2:4.2.17
 - [x] pj2:4.6.8
 - [x] pj2:4.7.9
 - [x] pj2:4.8.9
 - [x] pj2:4.10.9
 - [x] pj2:4.10.12
 - [x] pj2:4.11.7
 - [x] pj2:4.12.9
 - [x] pj2:4.12.12
 - [x] pj2:4.12.17
 - [x] pj2:4.13.9
 - [x] pj2:4.13.14
 - [x] pj2:4.15.9
 - [x] pj2:4.16.6
 - [x] pj2:4.16.9
 - [x] pj2:4.19.6
 - [x] pj2:4.19.8
 - [x] pj2:4.21.8
 - [x] pj2:4.21.9
 - [x] pj2:4.22.6
 - [x] pj2:4.24.6
 - [x] pj2:4.25.6
 - [x] pj2:4.26.6 
 - [x] pj3:4.2.7
 - [x] pj3:4.2.9
 - [x] pj3:4.2.11
 - [x] pj3:4.2.26
 - [x] pj3:4.2.29
 - [x] pj3:4.2.32

**Comment by brahmali** [comment]
Sādhu!!!
