### ISSUE TITLE
Even more Vinaya issues

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#2398]
Please remove bold or bold-face from the following segments:

**Bhikkhus**:
**Sg.6**: 2.2.3 + 2.2.4 + 2.2.30 + 2.2.31
**Sg.7**: 2.13 + 2.14 + 2.43 + 2.44

**Np.1**: 3.2.6 + 3.2.7 + 3.2.15 + 3.2.16 + 3.2.20 + 3.2.21 + 3.2.22 + 3.2.24 + 3.2.25 + 3.2.29
**Np.18**: 2.18 + 2.19 + 2.20 + 2.51 + 2.52
**Np.19**: 2.28 + 2.29 + 2.30 + 2.61 + 2.62
**Np.21**: 3.17 + 3.18 + 3.2.16 + 3.26 + 3.27 + 3.31 + 3.32 + 3.33 + 3.40 + 3.51 + 3.52 + 3.53 + 3.54
**Np.22**: 1.1.23 + 1.2.9 + 2.1.20 + 2.1.23 + 2.1.24 + 2.1.46

**Pc.21**: 2.26

**Bhikkhunīs**:
**Pj.7**: 2.1.26 + 2.1.27 + 2.1.28 + 2.1.34 + 2.1.35 + 2.1.36 + 2.1.37 

**Sg.10**: 2.1.13 + 2.1.14 + 2.1.15 + 2.1.16 + 2.1.17 + 2.1.18 + 2.1.25 + 2.1.26 + 2.1.27 + 2.1.28 + 2.1.29 + 2.1.30 
**Sg.11**: 2.1.17 + 2.1.18 + 2.1.19 + 2.1.26 + 2.1.27 + 2.1.28
**Sg.12**: 2.1.19 + 2.1.20 + 2.1.27 + 2.1.28
**Sg.13**: 2.25 + 2.26 + 2.27 + 2.28 + 2.35 + 2.36 + 2.37 + 2.38

**Np.1**: 2.1.22 + 2.1.30 + 2.1.34 + 2.1.35+ 2.1.36 + 2.1.38 + 2.1.39 + 2.1.43

**Pc.36**: 2.1.15 + 2.1.16 + 2.1.17 + 2.1.24+ 2.1.25 + 2.1.26
**Pc.63**: 1.15 + 1.16 + 1.17 + 1.18+ 1.19
**Pc.64**: 1.19
**Pc.66**: 1.12 + 1.15
**Pc.67**: 1.16 + 1.18 + 1.19 + 1.20 + 1.21
**Pc.72**: 1.17
**Pc.73**: 1.19
**Pc.75**: 1.19

And add paragraph after the following segments:

- [x] **Bhī.pc.63**: 1.15
- [x] **Bhī.pc.67**: 1.18

**Comment by sujato** [comment]
- [x] bu-vb-ss6:2.2.3
 - [x] bu-vb-ss6:2.2.4
 - [x] bu-vb-ss6:2.2.30
 - [x] bu-vb-ss6:2.2.31
 - [x] bu-vb-ss7:2.13
 - [x] bu-vb-ss7:2.14
 - [x] bu-vb-ss7:2.43
 - [x] bu-vb-ss7:2.44
 - [x] bu-vb-np1:3.2.6
 - [x] bu-vb-np1:3.2.7
 - [x] bu-vb-np1:3.2.15
 - [x] bu-vb-np1:3.2.16
 - [x] bu-vb-np1:3.2.20
 - [x] bu-vb-np1:3.2.21
 - [x] bu-vb-np1:3.2.22
 - [x] bu-vb-np1:3.2.24
 - [x] bu-vb-np1:3.2.25
 - [x] bu-vb-np1:3.2.29
 - [x] bu-vb-np18:2.18
 - [x] bu-vb-np18:2.19
 - [x] bu-vb-np18:2.20
 - [x] bu-vb-np18:2.51
 - [x] bu-vb-np18:2.52
 - [x] bu-vb-np19:2.28
 - [x] bu-vb-np19:2.29
 - [x] bu-vb-np19:2.30
 - [x] bu-vb-np19:2.61
 - [x] bu-vb-np19:2.62
 - [x] bu-vb-np21:3.17
 - [x] bu-vb-np21:3.18
 - [x] bu-vb-np21:3.2.16
 - [x] bu-vb-np21:3.26
 - [x] bu-vb-np21:3.27
 - [x] bu-vb-np21:3.31
 - [x] bu-vb-np21:3.32
 - [x] bu-vb-np21:3.33
 - [x] bu-vb-np21:3.40
 - [x] bu-vb-np21:3.51
 - [x] bu-vb-np21:3.52
 - [x] bu-vb-np21:3.53
 - [x] bu-vb-np21:3.54
 - [x] bu-vb-np22:1.1.23
 - [x] bu-vb-np22:1.2.9
 - [x] bu-vb-np22:2.1.20
 - [x] bu-vb-np22:2.1.23
 - [x] bu-vb-np22:2.1.24
 - [x] bu-vb-np22:2.1.46
 - [x] bu-vb-pc21:2.26
 - [x] bi-vb-pj7:2.1.26
 - [x] bi-vb-pj7:2.1.27
 - [x] bi-vb-pj7:2.1.28
 - [x] bi-vb-pj7:2.1.34
 - [x] bi-vb-pj7:2.1.35
 - [x] bi-vb-pj7:2.1.36
 - [x] bi-vb-pj7:2.1.37
 - [x] bi-vb-ss10:2.1.13
 - [x] bi-vb-ss10:2.1.14
 - [x] bi-vb-ss10:2.1.15
 - [x] bi-vb-ss10:2.1.16
 - [x] bi-vb-ss10:2.1.17
 - [x] bi-vb-ss10:2.1.18
 - [x] bi-vb-ss10:2.1.25
 - [x] bi-vb-ss10:2.1.26
 - [x] bi-vb-ss10:2.1.27
 - [x] bi-vb-ss10:2.1.28
 - [x] bi-vb-ss10:2.1.29
 - [x] bi-vb-ss10:2.1.30
 - [x] bi-vb-ss11:2.1.17
 - [x] bi-vb-ss11:2.1.18
 - [x] bi-vb-ss11:2.1.19
 - [x] bi-vb-ss11:2.1.26
 - [x] bi-vb-ss11:2.1.27
 - [x] bi-vb-ss11:2.1.28
 - [x] bi-vb-ss12:2.1.19
 - [x] bi-vb-ss12:2.1.20
 - [x] bi-vb-ss12:2.1.27
 - [x] bi-vb-ss12:2.1.28
 - [x] bi-vb-ss13:2.25
 - [x] bi-vb-ss13:2.26
 - [x] bi-vb-ss13:2.27
 - [x] bi-vb-ss13:2.28
 - [x] bi-vb-ss13:2.35
 - [x] bi-vb-ss13:2.36
 - [x] bi-vb-ss13:2.37
 - [x] bi-vb-ss13:2.38
 - [x] bi-vb-np1:2.1.22
 - [x] bi-vb-np1:2.1.30
 - [x] bi-vb-np1:2.1.34
 - [x] bi-vb-np1:2.1.35
 - [x] bi-vb-np1:2.1.36
 - [x] bi-vb-np1:2.1.38
 - [x] bi-vb-np1:2.1.39
 - [x] bi-vb-np1:2.1.43
 - [x] bi-vb-pc36:2.1.15
 - [x] bi-vb-pc36:2.1.16
 - [x] bi-vb-pc36:2.1.17
 - [x] bi-vb-pc36:2.1.24
 - [x] bi-vb-pc36:2.1.25
 - [x] bi-vb-pc36:2.1.26
 - [x] bi-vb-pc63:1.15
 - [x] bi-vb-pc63:1.16
 - [x] bi-vb-pc63:1.17
 - [x] bi-vb-pc63:1.18
 - [x] bi-vb-pc63:1.19
 - [x] bi-vb-pc64:1.19
 - [x] bi-vb-pc66:1.12
 - [x] bi-vb-pc66:1.15
 - [x] bi-vb-pc67:1.16
 - [x] bi-vb-pc67:1.18
 - [x] bi-vb-pc67:1.19
 - [x] bi-vb-pc67:1.20
 - [x] bi-vb-pc67:1.21
 - [x] bi-vb-pc72:1.17
 - [x] bi-vb-pc73:1.19
 - [x] bi-vb-pc75:1.19
