### ISSUE TITLE
Accept to publish and other issues

### ISSUE THREAD

**Issue by renaldoaluska** [suttacentral/bilara-data#2648]
1. When clicking the "accept" button to publish, this happens:

<img width="341" alt="image" src="https://github.com/suttacentral/bilara-data/assets/21968935/7d009a18-50b5-4c7e-8740-acc8ff386f88">

2. And for the live blurbs, why does it show the underscores instead of executing the code as an actual italic?

<img width="495" alt="image" src="https://github.com/suttacentral/bilara-data/assets/21968935/e7044a0d-ed0a-4810-b832-394292f23ff4">

3. I'm not sure whether these issues are supposed to be reported here or elsewhere but some sutta titles are truncated.

<img width="560" alt="image" src="https://github.com/suttacentral/bilara-data/assets/21968935/243cf319-4bdd-4242-95c3-0e6507535394">

<img width="512" alt="image" src="https://github.com/suttacentral/bilara-data/assets/21968935/08edfd5e-62b5-4838-ad7c-bff61578d3ee">

In `mn29`, the title is supposed to be "Khotbah panjang tentang Perumpamaan Inti Kayu" but the "Perumpamaan Inti Kayu" part is in the text instead of the title.

This kind of issue also applies to `mn37`, `mn38`, `mn62`, `mn63`, `mn64`, `mn147`.

Thanks in advance :)

**Comment by ccronje** [comment]
Thanks @renaldoaluska
Is 1. happening every time or was it that one time?
For 2. can you please list all the blurbs affected? I'll see if re-running the github workflow fixes it.
For 3. we'll need to ask @ihongda to investigate.

**Comment by renaldoaluska** [comment]
1) It used to happen everytime but now it’s fixed, thanks!

2) MN: 6, 7, 8, 11, 14, 38, 59, 62, 102, 109, 115, 118, 119, 135.

3) Sure, thanks!

**Comment by ihongda** [comment]
Hi @renaldoaluska @ccronje 

> 2. And for the live blurbs, why does it show the underscores instead of executing the code as an actual italic?

This issue has been resolved by redeploying the data.

>I'm not sure whether these issues are supposed to be reported here or elsewhere but some sutta titles are truncated.

The title is taken from the `h1` tag in the html file, so to fix this, need to edit the source file:

https://github.com/suttacentral/sc-data/blob/master/html_text/id/pli/sutta/mn/mn29.html

**Comment by ccronje** [comment]
> This issue has been resolved by redeploying the data.

Thanks @ihongda!

> The title is taken from the h1 tag in the html file, so to fix this, need to edit the source file:
https://github.com/suttacentral/sc-data/blob/master/html_text/id/pli/sutta/mn/mn29.html

Should a new issue be created on [sc-data](https://github.com/suttacentral/sc-data/issues) and Bhante Sujato copied in for further discussion?

**Comment by ihongda** [comment]
> Should a new issue be created on [sc-data](https://github.com/suttacentral/sc-data/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and Bhante Sujato copied in for further discussion?

hmm, I agree, the structure and content need to be slightly changed, please ask Bhante 😄
