### ISSUE TITLE
Vinaya corrections

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#2649]
**Kd.12:**

1.4.15: this should be item number 73, not 65.

9.1.37 - 9.1.39: should form a single segment, as elsewhere (they are part of the same list number)
9.1.40.1 - 9.1.40.3: ditto
9.1.41 - 9.1.43: ditto
9.1.44.1 - 9.1.44.3: ditto
9.1.44.4 - 9.1.45: ditto

9.1.66 - 9.1.73: should be individual list items

9.1.58: this item number should be set at 9 greater than at 9.1.57, and the following segments need to be adjusted accordingly.

**Comment by sujato** [comment]
Kd.12:

- [x] 1.4.15: this should be item number 73, not 65.

9.1.37 - 9.1.39: should form a single segment, as elsewhere (they are part of the same list number)
9.1.40.1 - 9.1.40.3: ditto
9.1.41 - 9.1.43: ditto
9.1.44.1 - 9.1.44.3: ditto
9.1.44.4 - 9.1.45: ditto

- [x] 9.1.66 - 9.1.73: should be individual list items

- [x] 9.1.58: this item number should be set at 9 greater than at 9.1.57, and the following segments need to be adjusted accordingly.

   - **this one needs to be checked!**

**Comment by sujato** [comment]
moved segment adjustments to separate issue.
