### ISSUE TITLE
There is no end to the Vinaya corrections

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#2736]
**remove bold at:** 

Bu-Ss.10: 2.28

Bu-Np.1: 4.11 + 4.12 + 4.13 + 4.14
Bu-Np.18: 2.51 + 2.52
Bu-Np.19: 2.61 + 2.62
Bu-Np.21: 3.51 + 3.52 + 3.53 + 3.54
Bu-Np.22: 2.1.20 + 2.1.46
Bu-Np.28: 2.33 + 2.34 + 2.35 + 2.36

Kd.13: 2.2.3-13 (remove kamma class) + 2.2.4-9 (remove kamma class) 

**add bold at:** 

Bu-Np.2: 2.13
Bu-Np.3: 1.14
Bu-Np.28: 1.14
Bu-Np.29: 1.1.7

Bu-Pc.7: 2.12
Bu-Pc.85: 2.10 + 3.10 + 4.7
Bu-Pc.89: 2.8

Bu-Pd.3: 1.10 + 2.11 + 3.13
Bu-Pd.4: 2.10

Bu-Sk.37: 2.8
Bu-Sk.57: 2.7
Bu-Sk.75: 2.4

Bi-Pc.5: 1.1.8
Bi-Pc.30: 1.1.8
Bi-Pc.84: 1.2.4
Bi-Pc.85: 1.2.3

Bi-Pd.1: 1.2.7
Bi-Pd.2-8: 1.2.7

Bi-Sk.75: 2.3

Kd.1: 57.1.5 + 60.1.5
Kd.4: 17.2.1 + 17.2.2+ 17.2.3 + 17.2.4 + 17.2.5 + 18.2.1 + 18.2.2 + 18.2.3 + 18.2.4 + 18.2.5 + 18.2.6 + 18.2.7
Kd.8: 27.2.2 + 27.2.3 + 27.3.4 + 27.3.5
Kd.14: 9.1.3 + 13.1.7 + 13.1.8 + 13.1.9 + 13.1.10 + 14.24.1 + 14.24.2 + 14.24.3 + 14.25.25 + 14.26.1 + 14.26.2 + 14.33.6 + 14.33.7 + 14.33.8 + 14.33.9 + 14.33.10 
Kd.16: 8.4 (make it part of the rule class of following segment)
Kd.19: 2.1.7 

**add paragraph after:**

Bu-Np.3: 1.1.13
Bu-Np.22: 2.1.19 + 2.1.45 + 2.1.46
Bu-Np.28: 1.1.13
Bu-Np.29: 1.1.6

Bu-pc.7: 2.11
Bu-pc.73: 2.1.13
Bu-pc.85: 2.9 + 3.9 + 4.6
Bu-pc.89: 2.7

Bu-pd.3: 1.9 + 2.10 + 3.12
Bu-pd.4: 2.9

Bu-Sk.37: 2.7
Bu-Sk.57: 2.6
Bu-Sk.75: 2.3

Bi-pc.5: 1.1.7
Bi-pc.14: 2.1.26
Bi-pc.30: 1.1.7
Bi-pc.84: 1.2.3
Bi-pc.85: 1.2.2

Bi-pd.1: 1.2.6
Bi-pd.2-8: 1.2.6

Bi-sk.75: 2.2

Kd.1: 38.7.1 + 38.10.1
Kd.5: 10.2.4
Kd.9: 4.7.2 + 4.8.1 + 4.9.3
Kd.13: 3.2.6 + 5.2.11 + 6.1.15 + 7.2.10 + 8.2.8 + 9.1.3 + 9.2.9 + 10.1.15 + 10.1.33 + 12.2.27 + 13.1.13 + 14.2.10 + 14.3.12 + 16.1.13 + 19.1.40 + 20.2.9 + 21.1.16 + 22.3.21 + 24.3.22 + 26.2.10 + 32.1.3
Kd.14: 9.1.3 + 14.24.3 + 14.27.18  + 14.28.35 + 14.29.30 + 14.33.5
Kd.16: 8.4
Kd.17: 3.16.9

**remove paragraph after:** 

Bu-Np.P10: 2.2.3
Bu-Np.21: 3.14
Bu-Np.27: 2.28

Bi-Np.1: 2.1.19

Bi-pc.14: 2.1.25

Kd.1: 7.9.5 + 12.3.2 + 14.3.5 + 27.2.1 + 29.1.6 + 39.4.6 + 49.4.6 + 54.4.1 + 57.2.9 + 60.1.3 + 63.3.10 + 76.5.7 + 76.6.1 + 76.8.8
Kd.2: 15.6.7
Kd.6: 15.4.6 + 15.6.10 + 23.2.8 + 23.4.3 + 31.5.2 + 32.1.6 + 34.6.12
Kd.7: 1.2.1 + 1.4.12
Kd.8: 1.2.7 + 1.35.10 + 27.2.1 + 27.3.3 + 31.1.11
Kd.9: 1.3.6 + 4.9.4
Kd.10: 1.4.2 + 2.3.7 + 2.16.11 + 2.16.18 + 5.6.19
Kd.11: 32.1.4 + 32.3.1 
Kd.13: 10.1.31 + 11.1.8 + 12.2.25 + 14.3.10 + 15.1.8 + 17.1.8 + 17.1.9 + 18.1.8 + 18.1.9 + 19.1.38 + 22.3.19
Kd.14: 4.1.9 + 4.4.14 + 8.1.43 + 9.1.16 
Kd.15: 8.2.3 + 14.4.6 + 20.3.1 + 20.6.1
Kd.16: 9.1.6
Kd.17: 3.3.1 + 3.16.7 + 4.1.13
Kd.19: 2.1.1 + 5.5.8
Kd.20: 1.4.2 + 1.6.5 + 2.2.6 + 3.1.12 + 17.4.7 + 17.4.8 + 17.4.14 + 17.5.20
Kd.21: 1.6.5 + 1.10.23

**add hr after:** 

Bu-Np.10: 2.2.3 + 2.2.11
Bu-Np.24: 2.9
Bu-Np.27: 2.29

Kd.1: 29.4.10

**remove hr after:** 

Bu-Np.3: 2.2.4
Bu-Np.4: 2.1.16
Bu-Np.8: 2.1.36

Bu-pc.4: 2.1.16
Bu-pc.21: 3.1.12
Bu-pc.28: 3.1.10 + 3.1.13
Bu-pc.29: 3.1.16
Bu-pc.32: 9.1.18
Bu-pc.33: 5.1.10
Bu-pc.35: 3.1.32
Bu-pc.36: 2.1.30
Bu-pc.37: 2.1.10
Bu-pc.38: 2.1.10
Bu-pc.39: 3.1.29
Bu-pc.40: 3.1.12
Bu-pc.47: 2.1.19
Bu-pc.48: 3.1.8 + 3.1.12
Bu-pc.50: 2.1.11
Bu-pc.65: 2.1.8

Bu-pd.1: 2.1.14
Bu-pd.3: 4.1.20
Bu-pd.4: 3.1.35

Bu-sk.25: 1.3.1
Bu-sk.29: 1.5
Bu-sk.34: 1.5
Bu-sk.37: 2.10.1
Bu-sk.42: 1.3.1
Bu-sk.45: 1.3.1
Bu-sk.55: 1.14.1
Bu-sk.56: 1.14.1
Bu-sk.57: 2.16
Bu-sk.58: 1.6
Bu-sk.59: 1.5
Bu-sk.60: 1.5
Bu-sk.63: 1.5
Bu-sk.66: 1.5
Bu-sk.67: 1.5
Bh-sk.69: 1.46.1

Bi-pc.1: 2.1.6
Bi-pc.7: 2.1.22
Bi-pc.10: 2.1.10
Bi-pc.20: 2.1.6
Bi-pc.26: 2.1.10
Bi-pc.34: 2.1.12
Bi-pc.40: 2.1.6
Bi-pc.41: 2.1.14
Bi-pc.60: 2.1.24
Bi-pc.77: 2.1.14
Bi-pc.78: 2.1.16

Bi-pd.1: 2.1.10
Bi-pd.2-8: 2.1.22

Kd.1: 20.23.5 + 20.24.5 + 38.4.8
Kd.2: 26.4.4 + 26.7.4 + 33.1.12
Kd.3: 5.9.32
Kd.4: 1.14.23 + 13.1.75 + 16.5.4 + 16.9.3 + 17.6.1
Kd.6: 13.2.29
Kd.8: 8.2.4 + 21.1.4
Kd.9: 4.6.11
Kd.10: 1.8.17 + 1.10.6 + 2.7.3 + 5.1.3
Kd.11: 4.1.10 + 10.1.84 + 14.1.44 + 14.2.10 + 20.1.5 + 22.2.13 + 26.1.44 + 27.1.46 + 29.1.26 + 31.1.89 + 31.1.148 + 31.1.194 + 33.1.44 + 33.1.78 + 34.2.24
Kd.12: 6.1.116 + 7.1.5
Kd.13: 26.2.32 + 26.3.27
Kd.14: 14.4.8 + 14.5.39 + 14.6.8 + 14.30.28 + 14.31.24
Kd.15: 6.1.36 + 11.2.16 + 24.2.24 + 24.3.24 + 35.5.8
Kd.16: 2.5.16 + 5.2.11
Kd.17: 3.2.23
Kd.20: 2.2.15 + 6.1.19 + 6..2.25 + 6.3.19 + 9.4.34 + 19.3.8 + 22.3.46 + 27.2.8

**move hr:**

Bu-Np.9: from after 2.40 to after 2.38
Bu-Np.21: from after 3.14 to after 3.13

Bi-Np.1: from after 2.1.19 to after 2.1.18

**remove bold-face at:** 

Kd.2: 27.1.8 + 27.1.9 + 27.2.1 + 27.2.2 + 27.6.8
Kd.4: 6.1.8 + 6.1.9 + 6.1.15 + 6.1.16 + 6.3.13

**second level of indentation required for sub-definitions, that is, sub-terms and sub-glosses:** 

Bu-pc.4: 2.1.9 - 2.1.16 (but 2.1.17 is a normal gloss and really a continuation of 2.1.8)
Bu-pc.10: 2.1.7 - 2.1.14
Bu-pc.11: 2.1.3 - 2.1.12
Bu-pc.54: 2.1.3 - 2.1.6
Bu-pc.59: 2.1.21 - 2.1.27
Bu-pc.69: 2.1.15 - 2.1.19
Bu-pc.70: 2.1.33 - 2.1.37
Bu-pc.85: 5.1.7 - 5.1.8

Bu-pd.3: 4.1.11 + 4.1.12 + 4.1.15 + 4.1.16
Bu-pd.4: 3.1.16-3.1.24 + 3.1.34-3.1.35

**other:** 

Bu-ss.2: after segment 2.1.23: change heading from “Summary” to “Sub-definitions” + after segment 2.2.1: remove heading “Sub-definitions”. 

Bu-pc.14: after segment 2.2.3: a comment intrudes into the text. 
Bu-pc.21: make segments 3.1.13 - 3.1.40 part of preceding gloss. 
Bu-pc.28: make segments 3.1.11 - 3.1.13 part of the immediately preceding gloss. 

Bi-pr.2: merge segments 1.6 and 1.7. 

Bi-pc.35: add paragraph marker after segment 2.2.6. 
Bi-pc.96: segment 2.2.2: comment displayed in all-caps.

Kd.1: italicise and indent: 20.24.1-5 + bullets: 38.5.3-38.7.2 + 38.8.2-38.10.2
Kd.2: italicise and indent: 33.1.12
Kd.4: italicise and indent: 12.1.12
Kd.7: indent: 7.1.2 + 7.1.7
Kd.9: indent: 7.6.16 + 7.7.16 + 7.8.16 + 7.9.16 + 7.10.16 + 7.11.16 + 7.14.16 + 7.14.32 + 7.14.48 + 7.14.64 + 7.18.81 + 7.14.98
Kd.13: indent: 32.1.4
Kd.15: italicise (to match other headings below): 1.0.2 + reduce heading level by one (these are sub-headings): 14.1.0.2 + 14.3.0 + 16.2.5.0 + 17.1.0
Kd.19: bullets (each range is one bullet point): 4.1.5-8/4.1.9-13/4.1.14-18/4.1.19-23/4.1.24-28
Kd.22: 2.8.23: asterisk needs to be moved up to segment 2.8.21 + 2.8.50: asterisk needs to be moved up to segment 2.8.45 + 2.8.109: asterisk needs to be moved up to segment 2.8.104

**Comment by sujato** [comment]
**remove bold at:** 

- [x] bu-vb-ss10:2.28
- [x] bu-vb-np1:4.11
- [x] bu-vb-np1:4.12
- [x] bu-vb-np1:4.13
- [x] bu-vb-np1:4.14
- [x] bu-vb-np18:2.51
- [x] bu-vb-np18:2.52
- [x] bu-vb-np19:2.61
- [x] bu-vb-np19:2.62
- [x] bu-vb-np21:3.51
- [x] bu-vb-np21:3.52
- [x] bu-vb-np21:3.53
- [x] bu-vb-np21:3.54
- [x] bu-vb-np22:2.1.20
- [x] bu-vb-np22:2.1.46
- [x] bu-vb-np28:2.33
- [x] bu-vb-np28:2.34
- [x] bu-vb-np28:2.35
- [x] bu-vb-np28:2.36
- [x] kd2:27.1.8
- [x] kd2:27.1.9 (plus add paragraph after this segment)
- [x] kd2:27.2.1 
- [x] kd2:27.2.2 (plus add paragraph after this segment)
- [x] kd4:6.1.8
- [x] kd4:6.1.9 (plus add paragraph after this segment)
- [x] kd4:6.1.15
- [x] kd4:6.1.16 (plus add paragraph after this segment)
- [x] kd13:2.2.3-13 (remove kamma class) 
- [x] kd13:4.2.4-9 (remove kamma class)

**Comment by sujato** [comment]
**add bold at:** 
- [x] bu-vb-np2:2.13 (rule class)
- [x] bu-vb-np3:1.1.14 (rule class + make into a separate paragraph)
- [x] bu-vb-np28:1.1.14 (rule class + make into a separate paragraph)
- [x] bu-vb-np29:1.1.7 (rule class + make into a separate paragraph)
- [x] bu-vb-pc7:2.12 (rule class + make into a separate paragraph)
- [x] bu-vb-pc85:2.10 (rule class + make into a separate paragraph)
- [x] bu-vb-pc85:3.10 (rule class + make into a separate paragraph)
- [x] bu-vb-pc85:4.7 (rule class + make into a separate paragraph)
- [x] bu-vb-pc89:2.8 (rule class + make into a separate paragraph)
- [x] bu-vb-pd3:1.10 (rule class + make into a separate paragraph)
- [x] bu-vb-pd3:2.11 (rule class + make into a separate paragraph)
- [x] bu-vb-pd3:3.13 (rule class + make into a separate paragraph)
- [x] bu-vb-pd4:2.10 (rule class + make into a separate paragraph)
- [x] bu-vb-sk37:2.8 (rule class + make into a separate paragraph)
- [x] bu-vb-sk57:2.7 (rule class + make into a separate paragraph)
- [x] bu-vb-sk75:2.4 (rule class + make into a separate paragraph)
- [x] bi-vb-pc5:1.1.8 (rule class + make into a separate paragraph)
- [x] bi-vb-pc30:1.1.8 (rule class + make into a separate paragraph)
- [x] bi-vb-pc84:1.2.4 (rule class + make into a separate paragraph)
- [x] bi-vb-pc85:1.2.3 (rule class + make into a separate paragraph)
- [x] bi-vb-pd1:1.2.7 (rule class + make into a separate paragraph)
- [x] bi-vb-pd.2-8:1.2.7 (rule class + make into a separate paragraph)
- [x] bi-vb-sk75:2.3 (rule class + make into a separate paragraph)
- [x] kd1:57.1.5 (rule class)
- [x] kd1:60.1.5 (rule class)
- [x] kd4:17.2.1
- [x] kd4:17.2.2
- [x] kd4:17.2.3
- [x] kd4:17.2.4
- [x] kd4:17.2.5
- [x] kd4:18.2.1
- [x] kd4:18.2.2
- [x] kd4:18.2.3
- [x] kd4:18.2.4
- [x] kd4:18.2.5
- [x] kd4:18.2.6
- [x] kd4:18.2.7
- [x] kd8:27.2.2 (rule class + remove paragraph from previous segment.)
- [x] kd8:27.2.3 (rule class)
- [x] kd8:27.3.4 (rule class + remove paragraph from previous segment.)
- [x] kd8:27.3.5 (rule class)
- [x] kd14:9.1.3-5 (rule class + add paragraph after 9.1.5)
- [x] kd14:13.1.7 (rule class)
- [x] kd14:13.1.8 (rule class)
- [x] kd14:13.1.9 (rule class)
- [x] kd14:13.1.10 (rule class)
- [x] kd14:14.24.1 (rule class)
- [x] kd14:14.24.2 (rule class)
- [x] kd14:14.24.3 (rule class)
- [x] kd14:14.24.4 (rule class)
- [x] kd14:14.24.5 (rule class + add paragraph after 14.24.5)
- [x] kd14:14.25.25 (rule class)
- [x] kd14:14.26.1 (rule class)
- [x] kd14:14.26.2 (rule class)
- [x] kd14:14.33.6 (rule class + add paragraph to previous segment)
- [x] kd14:14.33.7 (rule class)
- [x] kd14:14.33.8 (rule class)
- [x] kd14:14.33.9 (rule class)
- [x] kd14:14.33.10 (rule class)
- [x] kd16:8.5 (make it part of the rule class of following segment)
- [x] kd19:2.1.7 (rule class)

**Comment by sujato** [comment]
**add paragraph after:**

- [x] bu-vb-np3:1.1.13
- [x] bu-vb-np28:1.1.13
- [x] bu-vb-np29:1.1.6
- [x] bu-vb-pc7:2.11
- [x] bu-vb-pc73:2.1.13
- [x] bu-vb-pc85:2.9
- [x] bu-vb-pc85:3.9
- [x] bu-vb-pc85:4.6
- [x] bu-vb-pc89:2.7
- [x] bu-vb-pd3:1.9
- [x] bu-vb-pd3:2.10
- [x] bu-vb-pd3:3.12
- [x] bu-vb-pd4:2.9
- [x] bu-vb-sk37:2.7
- [x] bu-vb-sk57:2.6
- [x] bu-vb-sk75:2.3
- [x] bi-vb-pc5:1.1.7
- [x] bi-vb-pc14:2.1.26
- [x] bi-vb-pc30:1.1.7
- [x] bi-vb-pc84:1.2.3
- [x] bi-vb-pc85:1.2.2
- [x] bi-vb-pd1:1.2.6
- [x] bi-vb-pd2-8:1.2.6
- [x] bi-vb-sk75:2.2
- [x] kd1:38.7.1
- [x] kd1:38.10.1
- [x] kd5:10.2.4
- [x] kd9:4.7.2
- [x] kd9:4.8.1
- [x] kd9:4.9.3
- [x] kd13:3.2.6
- [x] kd13:5.2.11
- [x] kd13:6.1.15
- [x] kd13:7.2.10
- [x] kd13:8.2.8
- [x] kd13:9.1.3
- [x] kd13:9.2.9
- [x] kd13:10.1.15
- [x] kd13:10.1.33
- [x] kd13:12.2.27
- [x] kd13:13.1.13
- [x] kd13:14.2.10
- [x] kd13:14.3.12
- [x] kd13:16.1.13
- [x] kd13:19.1.40
- [x] kd13:20.2.9
- [x] kd13:21.1.16
- [x] kd13:22.3.21
- [x] kd13:24.3.22
- [x] kd13:26.2.10
- [x] kd13:32.1.3
- [x] kd14:9.1.3
- [x] kd14:14.24.3
- [x] kd14:14.27.18
- [x] kd14:14.28.35
- [x] kd14:14.29.30
- [x] kd14:14.33.5
- [x] kd16:8.4
- [x] kd17:3.16.9
- [x] kd20:2.2.3

**Comment by sujato** [comment]
**remove paragraph after:** 

- [x] bu-vb-np21:3.14 (the purpose here is to move the hr to after segment 3.13, and then join 3.14 and 3.15 into a single paragraph)
- [x] bi-vb-np1:2.1.19 (the purpose here is to move the hr to after segment 2.1.18, and then join 2.19 and 2.20 into a single paragraph)
- [x] kd1:12.3.2
- [x] kd1:27.2.1
- [x] kd1:29.1.6
- [x] kd1:39.4.7
- [x] kd1:49.4.6
- [x] kd1:57.2.9
- [x] kd1:60.1.3
- [x] kd1:63.3.10
- [x] kd1:76.5.7
- [x] kd1:76.6.1
- [x] kd1:76.8.8
- [x] kd2:15.6.7
- [x] kd6:15.4.6
- [x] kd6:15.6.10
- [x] kd6:23.2.8
- [x] kd6:31.5.2
- [x] kd6:32.1.6
- [x] kd6:34.6.12
- [x] kd7:1.2.1
- [x] kd7:1.4.12 (this should be remove hr)
- [x] kd8:1.2.7
- [x] kd8:1.35.10
- [x] kd8:27.2.1 (the next  segment becomes part of the rule class)
- [x] kd8:27.3.3 (the next  segment becomes part of the rule class)
- [x] kd8:31.1.11
- [x] kd9:4.9.4
- [x] kd10:1.4.2
- [x] kd10:2.16.11
- [x] kd10:2.16.18
- [x] kd10:5.6.19
- [x] kd11:32.1.4
- [x] kd11:32.3.1 
- [x] kd13:10.1.31
- [x] kd13:11.1.8
- [x] kd13:12.2.25
- [x] kd13:14.3.10
- [x] kd13:15.1.8
- [x] kd13:17.1.8
- [x] kd13:17.1.9
- [x] kd13:18.1.8
- [x] kd13:18.1.9
- [x] kd13:19.1.38
- [x] kd13:22.3.19
- [x] kd14:4.1.9
- [x] kd14:4.4.14
- [x] kd14:8.1.43 (this should be remove hr)
- [x] kd14:9.1.16 (this should be remove hr)
- [x] kd15:8.2.3
- [x] kd15:14.4.6 (the next  segment becomes part of the rule class)
- [x] kd15:20.3.1
- [x] kd15:20.6.1
- [x] kd16:9.1.6
- [x] kd17:3.3.1
- [x] kd17:3.16.7
- [x] kd19:2.1.1
- [x] kd19:5.5.8
- [x] kd20:1.5.2
- [x] kd20:1.6.4
- [x] kd20:2.2.6
- [x] kd20:17.4.7
- [x] kd20:17.4.8
- [x] kd20:17.4.14
- [x] kd20:17.5.20
- [x] kd21:1.6.5
- [x] kd21:1.10.23 (this should be remove hr)

**Comment by sujato** [comment]
**add hr after:** 
- [x] bu-vb-np10:2.2.3
- [x] bu-vb-np10:2.2.11
- [x] bu-vb-np24:2.9
- [x] bu-vb-np27:2.29
- [x] kd1:29.4.10

**Comment by sujato** [comment]
**remove hr after:** 
- [x] bu-vb-np3:2.2.4
- [x] bu-vb-np4:2.1.16
- [x] bu-vb-np8:2.1.36
- [x] bu-vb-pc4:2.1.16
- [x] bu-vb-pc21:3.1.12
- [x] bu-vb-pc28:3.1.10
- [x] bu-vb-pc28:3.1.13
- [x] bu-vb-pc29:3.1.16
- [x] bu-vb-pc32:9.1.18
- [x] bu-vb-pc33:5.1.10
- [x] bu-vb-pc35:3.1.32
- [x] bu-vb-pc36:2.1.30
- [x] bu-vb-pc37:2.1.10
- [x] bu-vb-pc38:2.1.10
- [x] bu-vb-pc39:3.1.29
- [x] bu-vb-pc40:3.1.12
- [x] bu-vb-pc47:2.1.19
- [x] bu-vb-pc48:3.1.8
- [x] bu-vb-pc48:3.1.12
- [x] bu-vb-pc50:2.1.11
- [x] bu-vb-pc65:2.1.8
- [x] bu-vb-pd1:2.1.14
- [x] bu-vb-pd3:4.1.20
- [x] bu-vb-pd4:3.1.35
- [x] bu-vb-sk25:1.3.1
- [x] bu-vb-sk29:1.5
- [x] bu-vb-sk34:1.5
- [x] bu-vb-sk37:2.10.1
- [x] bu-vb-sk42:1.3.1
- [x] bu-vb-sk45:1.3.1
- [x] bu-vb-sk55:1.14.1
- [x] bu-vb-sk56:1.14.1
- [x] bu-vb-sk57:2.16
- [x] bu-vb-sk58:1.6
- [x] bu-vb-sk59:1.5
- [x] bu-vb-sk60:1.5
- [x] bu-vb-sk63:1.5
- [x] bu-vb-sk66:1.5
- [x] bu-vb-sk67:1.5
- [x] bh-sk69:1.46.1
- [x] bi-vb-pc1:2.1.6
- [x] bi-vb-pc7:2.1.22
- [x] bi-vb-pc10:2.1.10
- [x] bi-vb-pc20:2.1.6
- [x] bi-vb-pc26:2.1.10
- [x] bi-vb-pc34:2.1.12
- [x] bi-vb-pc40:2.1.6
- [x] bi-vb-pc41:2.1.14
- [x] bi-vb-pc60:2.1.24
- [x] bi-vb-pc77:2.1.14
- [x] bi-vb-pc78:2.1.16
- [x] bi-vb-pd1:2.1.10
- [x] bi-vb-pd2-8:2.1.22
- [x] kd1:20.23.5
- [x] kd1:20.24.5
- [x] kd1:38.4.8
- [x] kd2:26.4.4
- [x] kd2:26.7.4
- [x] kd2:33.1.12
- [x] kd3:5.9.32
- [x] kd4:1.14.23
- [x] kd4:13.1.75
- [x] kd4:16.5.4
- [x] kd4:16.9.3
- [x] kd4:17.6.1
- [x] kd6:13.2.29
- [x] kd8:8.2.4
- [x] kd8:21.1.4
- [x] kd9:4.6.11
- [x] kd10:1.8.17
- [x] kd10:1.10.6
- [x] kd10:2.7.3
- [x] kd10:5.1.3
- [x] kd11:4.1.10
- [x] kd11:10.1.84
- [x] kd11:14.1.44
- [x] kd11:14.2.10
- [x] kd11:20.1.5
- [x] kd11:22.2.13
- [x] kd11:26.1.44
- [x] kd11:27.1.46
- [x] kd11:29.1.26
- [x] kd11:31.1.89
- [x] kd11:31.1.148
- [x] kd11:31.1.194
- [x] kd11:33.1.44
- [x] kd11:33.1.78
- [x] kd11:34.2.24
- [x] kd12:6.1.116
- [x] kd12:7.1.5
- [x] kd13:26.2.32
- [x] kd13:26.3.27
- [x] kd14:14.4.8
- [x] kd14:14.5.39
- [x] kd14:14.6.8
- [x] kd14:14.30.28
- [x] kd14:14.31.24
- [x] kd15:6.1.36
- [x] kd15:11.2.16
- [x] kd15:24.2.24
- [x] kd15:24.3.24
- [x] kd15:35.5.8
- [x] kd16:2.5.16
- [x] kd16:5.2.11
- [x] kd17:3.2.23
- [x] kd20:2.2.15
- [x] kd20:6.1.19
- [x] kd20:6..2.25
- [x] kd20:6.3.19
- [x] kd20:9.4.34
- [x] kd20:19.3.8
- [x] kd20:22.3.46
- [x] kd20:27.2.8

**Comment by sujato** [comment]
**move hr:**
- [x] bu-vb-np9:2.40 from after  to after 2.38
- [x] bu-vb-np21:3.14 from after  to after 3.13
- [x] bi-vb-np1:2.1.19 from after  to after 2.1.18

**Comment by sujato** [comment]
moved to https://github.com/suttacentral/bilara-data/issues/2818

**Comment by sujato** [comment]
**other:** 

- [x] bu-vb-pc14:2.2.3 after segment : a comment intrudes into the text. 
- [x] bu-vb-pc21: make segments 3.1.13 - 3.1.40 part of preceding gloss. 
- [x] bu-vb-pc28: make segments 3.1.11 - 3.1.13 part of the immediately preceding gloss. 
- [x] bi-vb-pc35:2.2.6 add paragraph marker after segment 
- [x] bi-vb-pc96:2.2.2 segment : comment displayed in all-caps.
     - this is a style problem rather than a data one, I have fixed the CSS
- [x] kd1: italicise and indent: 20.24.1-5 + bullets: 38.5.3-38.7.2 + 38.8.2-38.10.2
    - mark 20.24.1-5 as uddana
- [x] kd2: italicise and indent: 33.1.12
    - mark as uddana
- [x] kd4: italicise and indent: 12.1.12
    - mark as uddana
- [x] kd7: indent: 7.1.2 + 7.1.7
    - these are already correctly marked as `'pe'`.
- [x] kd9: indent: 7.6.16 + 7.7.16 + 7.8.16 + 7.9.16 + 7.10.16 + 7.11.16 + 7.14.16 + 7.14.32 + 7.14.48 + 7.14.64 + 7.18.81 + 7.14.98
    - already correct
- [x] kd13: indent: 32.1.4
    - already correct
- [x] kd15: italicise (to match other headings below): 1.0.2 
- [x] kd15: reduce heading level by one (these are sub-headings): 14.1.0.2 + 14.3.0 + 16.2.5.0 + 17.1.0
- [x] kd19: bullets (each range is one bullet point): 4.1.5-8/4.1.9-13/4.1.14-18/4.1.19-23/4.1.24-28
    - make `<ol>` since it is numbered.
- [x] kd22: 2.8.23: asterisk needs to be moved up to segment 2.8.21 + 2.8.50: asterisk needs to be moved up to segment 2.8.45 + 2.8.109: asterisk needs to be moved up to segment 2.8.104
