### ISSUE TITLE
Parivara layout

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#2765]
**Add hr after:**
 - [x] kd.14:1.1.20
 - [x] pvr4:39.14
 - [x] pvr4:41.11
 - [x] pvr4:43.11
 - [x] pvr4:45.11
 - [x] pvr4:47.11
 - [x] pvr4:65.11
 - [x] pvr4:67.11
 - [x] pvr4:69.11
 - [x] pvr4:74.13
 - [x] pvr4:76.13
 - [x] pvr4:78.11
 - [x] pvr4:80.11
 - [x] pvr5:8.20
 - [x] pvr5:99.2
 - [x] pvr5:105.3
 - [x] pvr5:108.3
 - [x] pvr5:115.4
 - [x] pvr5:121.6
 - [x] pvr5:124.6
 - [x] pvr5:134.2
 - [x] pvr5:141.2
 - [x] pvr5:146.1
 - [x] pvr5:164.1
 - [x] pvr11:4.4
 - [x] pvr11:22.12
 - [x] pvr11:25.18
 - [x] pvr11:28.14
 - [x] pvr11:47.12
 - [x] pvr11:52.1
 - [x] pvr11:57.2
 - [x] pvr11:62.2
 - [x] pvr16:15.8
 - [x] pvr16:21.2
 - [x] pvr16:22.9
 - [x] pvr16:23.9
 - [x] pvr18:1.13
 - [x] pvr21:7.8
 - [x] pvr21:15.11
 - [x] pvr21:43.9

**Remove hr after:**
 - [x] pvr16:4.26
 - [x] pvr16:6.3
 - [x] pvr16:35.2
 - [x] pvr21:6.6

**Add paragraph after:**
 - [x] pvr1.8:2.1
 - [x] pvr1.8:4.2
 - [x] pvr1.16:1.6
 - [x] pvr1.16:1.12
 - [x] pvr1.16:2.3
 - [x] pvr1.16:2.9
 - [x] pvr2.8:2.5
 - [x] pvr2.8:4.5
 - [x] pvr2.16:2.5
 - [x] pvr2.16:4.5
 - [x] pvr5:26.2
 - [x] pvr5:35.2
 - [x] pvr5:129.1
 - [x] pvr5:135.1
 - [x] pvr5:142.1
 - [x] pvr5:146.1
 - [x] pvr7:8.20
 - [x] pvr7:10.16
 - [x] pvr7:10.32
 - [x] pvr7:10.54
 - [x] pvr7:25.3
 - [x] pvr7:25.6
 - [x] pvr7:25.9
 - [x] pvr7:25.12
 - [x] pvr7:25.15
 - [x] pvr7:25.18
 - [x] pvr7:25.21
 - [x] pvr7:26.3
 - [x] pvr7:26.6
 - [x] pvr7:26.9
 - [x] pvr7:26.12
 - [x] pvr7:26.15
 - [x] pvr7:26.18
 - [x] pvr7:26.22
 - [x] pvr7:26.24
 - [x] pvr7:26.28
 - [x] pvr7:26.32
 - [x] pvr7:26.34
 - [x] pvr7:26.37
 - [x] pvr7:27.8
 - [x] pvr7:27.11
 - [x] pvr7:27.14
 - [x] pvr7:28.2
 - [x] pvr7:28.4
 - [x] pvr7:28.6
 - [x] pvr7:28.8
 - [x] pvr7:28.10
 - [x] pvr7:28.12
 - [x] pvr7:29.2
 - [x] pvr7:33.2
 - [x] pvr7:46.4
 - [x] pvr7:46.8
 - [x] pvr7:46.12
 - [x] pvr7:46.16
 - [x] pvr7:46.20
 - [x] pvr7:47.4
 - [x] pvr7:47.6
 - [x] pvr7:48.2
 - [x] pvr7:48.7
 - [x] pvr7:48.11
 - [x] pvr7:50.4
 - [x] pvr7:50.8
 - [x] pvr7:50.9
 - [x] pvr7:50.10
 - [x] pvr7:50.11
 - [x] pvr7:50.12
 - [x] pvr7:50.18
 - [x] pvr7:51.4
 - [x] pvr7:51.8
 - [x] pvr7:51.12
 - [x] pvr7:51.16
 - [x] pvr7:51.20
 - [x] pvr7:51.24
 - [x] pvr7:51.28
 - [x] pvr7:51.32
 - [x] pvr7:63.8
 - [x] pvr7:63.10
 - [x] pvr7:63.12
 - [x] pvr7:63.14
 - [x] pvr7:63.24
 - [x] pvr7:63.26
 - [x] pvr7:63.28
 - [x] pvr7:63.30
 - [x] pvr7:63.32
 - [x] pvr7:63.57
 - [x] pvr7:63.59
 - [x] pvr7:64.2
 - [x] pvr7:64.4
 - [x] pvr7:64.6
 - [x] pvr7:64.8
 - [x] pvr7:64.10
 - [x] pvr7:64.12
 - [x] pvr7:64.14
 - [x] pvr7:64.16
 - [x] pvr7:64.18
 - [x] pvr7:64.20
 - [x] pvr7:64.22
 - [x] pvr7:64.24
 - [x] pvr7:64.26
 - [x] pvr7:64.28
 - [x] pvr7:64.30
 - [x] pvr7:65.2
 - [x] pvr7:66.2
 - [x] pvr7:66.4
 - [x] pvr7:66.6
 - [x] pvr7:66.8
 - [x] pvr7:66.10
 - [x] pvr7:66.12
 - [x] pvr7:66.14
 - [x] pvr7:66.16
 - [x] pvr7:66.18
 - [x] pvr7:66.20
 - [x] pvr7:66.22
 - [x] pvr7:67.2
 - [x] pvr7:67.4
 - [x] pvr7:67.6
 - [x] pvr7:67.8
 - [x] pvr7:67.10
 - [x] pvr7:68.2
 - [x] pvr7:68.4
 - [x] pvr7:68.10
 - [x] pvr7:68.12
 - [x] pvr7:68.14
 - [x] pvr7:82.2
 - [x] pvr7:83.7
 - [x] pvr7:84.2
 - [x] pvr7:85.2
 - [x] pvr7:86.2
 - [x] pvr7:87.2
 - [x] pvr7:88.2
 - [x] pvr7:144.19
 - [x] pvr11:44.7
 - [x] pvr11:48.1
 - [x] pvr11:53.1
 - [x] pvr11:58.1
 - [x] pvr11:63.1
 - [x] pvr13:1.2
 - [x] pvr13:1.5
 - [x] pvr13:1.7
 - [x] pvr13:1.15
 - [x] pvr13:1.22
 - [x] pvr13:1.30
 - [x] pvr13:5.2
 - [x] pvr13:5.4
 - [x] pvr13:7.4
 - [x] pvr13:7.7
 - [x] pvr13:7.11
 - [x] pvr13:7.14
 - [x] pvr15:12.3
 - [x] pvr15:13.5
 - [x] pvr15:14.4
 - [x] pvr15:15.3
 - [x] pvr15:31.2
 - [x] pvr15:31.5
 - [x] pvr15:31.7
 - [x] pvr15:31.13
 - [x] pvr15:31.20
 - [x] pvr15:31.27
 - [x] pvr16:8.1
 - [x] pvr16:9.4
 - [x] pvr16:9.8
 - [x] pvr16:9.12
 - [x] pvr16:9.16
 - [x] pvr16:9.20
 - [x] pvr16:22.4
 - [x] pvr16:22.6
 - [x] pvr16:23.4
 - [x] pvr16:23.6
 - [x] pvr16:24.4
 - [x] pvr16:24.6
 - [x] pvr16:36.7
 - [x] pvr16:36.11
 - [x] pvr16:36.15
 - [x] pvr16:37.4
 - [x] pvr16:37.8
 - [x] pvr16:54.3
 - [x] pvr16:54.9
 - [x] pvr16:54.12
 - [x] pvr16:55.2
 - [x] pvr17:138.1
 - [x] pvr17:140.1
 - [x] pvr17:141.1
 - [x] pvr17:142.1
 - [x] pvr17:143.1
 - [x] pvr18:1.4
 - [x] pvr18:1.7
 - [x] pvr18:1.10
 - [x] pvr21:2.6 (but keep as gloss)
 - [x] pvr21:2.11 (but keep as gloss)
 - [x] pvr21:2.15 (but keep as gloss)
 - [x] pvr21:14.4
 - [x] pvr21:15.2
 - [x] pvr21:15.5
 - [x] pvr21:15.8

 **Remove paragraph after:**
 - [x] pvr13:5.12
 - [x] pvr16:16.3
 - [x] pvr16:17.3
 - [x] pvr16:18.3
 - [x] pvr17:55.3
 - [x] pvr17:57.3
 - [x] pvr17:60.3
 - [x] pvr17:63.3
 - [x] pvr17:71.3
 - [x] pvr17:74.3
 - [ ] pvr17:88.3
 - [x] pvr17:89.3
 - [x] pvr17:90.4
 - [x] pvr17:91.4
 - [x] pvr17:92.4
 - [x] pvr17:99.3
 - [x] pvr17:102.6
 - [x] pvr17:103.5
 - [x] pvr17:104.5
 - [x] pvr17:105.5
 - [x] pvr17:106.5
 - [x] pvr17:113.3
 - [x] pvr17:115.3
 - [x] pvr17:117.3
 - [x] pvr17:119.3
 - [x] pvr17:121.3
 - [x] pvr17:127.11
 - [x] pvr17:136.3
 - [x] pvr17:188.3
 - [x] pvr17:196.1
 - [x] pvr17:197.3
 - [x] pvr17:207.3
 - [x] pvr17:207.4
 - [x] pvr17:207.5
 - [x] pvr17:207.6
 - [x] pvr17:208.3
 - [x] pvr17:208.4
 - [x] pvr17:208.5
 - [x] pvr17:208.6
 - [x] pvr17:209.3
 - [x] pvr17:209.4
 - [x] pvr17:209.5
 - [x] pvr17:209.6
 - [x] pvr17:219.3
 - [x] pvr17:219.4
 - [x] pvr17:219.5
 - [x] pvr17:219.6
 - [x] pvr17:220.3
 - [x] pvr17:220.4
 - [x] pvr17:220.5
 - [x] pvr17:220.6
 - [x] pvr17:221.3
 - [x] pvr17:221.4
 - [x] pvr17:221.5
 - [x] pvr17:221.6
 - [x] pvr17:227.3
 - [x] pvr17:232.3
 - [x] pvr17:243.3

**Merge with preceding paragraph**
 - [x] pvr10:35.1 + pvr10:35.2
 - [x] pvr10:37.1 + pvr10:37.2

**Merge into a single paragraph:**
 - [x] pvr4:18.1-pvr4:23.2

**Other:**
 - [x] pvr2.1:29.4 (this segment needs to be included in the verse html)
 - [x] pvr4:30.6: the font changes at this point, but it should not
 - [x] pvr.16:5.1-pvr16:5.8: make this part of gloss in previous paragraph, but keep as separate paragraph
 - [x] pvr16:36.1-pvr16:36.19: this should all be part of the preceding gloss, but maintain paragraph break.

**Comment by sujato** [comment]
>Remove paragraph after

Most of these were correct as-is and I made no change. I did make several changes to properly articulate the abbreviated paragraphs esp. in pvr 17, and I also corrected the position of the data-counters.

>pvr17:88.3

There is no paragraph, is this a typo?

>Merge with preceding paragraph
>
 >pvr10:35.1 + pvr10:35.2
 <pvr10:37.1 + pvr10:37.2

These are two-lined gatha, so no change.

**Comment by brahmali** [comment]
First of all, thanks so much for all this! It's great to get it done!

> There is no paragraph, is this a typo?

There is a paragraph on SC, but nothing in the json file. Hopefully it will be fine at the update.

> These are two-lined gatha, so no change.

Hokay.
