### ISSUE TITLE
remove Pli Tv and Vb from the processed Vinaya links in comments

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#2899]
We process the text UIDs in comments to create a readable version. Eg. `mn1` becomes MN 1. 

In the Vinaya this is problematic, as the UIDs are quite long. The reason they are long is to disambiguate the different Vinaya editions. But this is not necessary in comments, as they obviously refer to the current edition.

Currently we have eg. a segment number 

```
pli-tv-bu-vb-ss13:2.45
```

This is marked up in comments as 

```
[pli-tv-bu-vb-ss13:2.45]()
```

This becomes the HTML:

```
<a href="https://suttacentral.net/pli-tv-bu-vb-ss13/en/brahmali#2.45">Pli Tv Bu Vb Ss 13:2.45</a>
```

Instead, remove Pli Tv and Vb and have the following:

```
<a href="https://suttacentral.net/pli-tv-bu-vb-ss13/en/brahmali#2.45">Bu Ss 13:2.45</a>
```

**Comment by sujato** [comment]
To make it more explicit, here are the changes:

- pli-tv-bu-vb-pj → Bu Pj
- pli-tv-bu-vb-ss → Bu Ss
- pli-tv-bu-vb-ay → Bu Ay
- pli-tv-bu-vb-np → Bu NP
- pli-tv-bu-vb-pc → Bu Pc
- pli-tv-bu-vb-pd → Bu Pd
- pli-tv-bu-vb-sk → Bu Sk
- pli-tv-bu-vb-as → Bu As
- pli-tv-bi-vb-pj → Bi Pj
- pli-tv-bi-vb-ss → Bi Ss
- pli-tv-bi-vb-ay → Bi Ay
- pli-tv-bi-vb-np → Bi NP
- pli-tv-bi-vb-pc → Bi Pc
- pli-tv-bi-vb-pd → Bi Pd
- pli-tv-bi-vb-sk → Bi Sk
- pli-tv-bi-vb-as → Bi As
- pli-tv-kd → Kd
- pli-tv-pvr → Pvr

**Comment by ihongda** [comment]
I have submitted the code and am observing the effect.

**Comment by ihongda** [comment]
It looks like the modification has taken effect.
