### ISSUE TITLE
fix vinaya edition links

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#2900]
## in body text

Vinaya links inside the text do not have the domain specified, hence they lead nowhere. This is in the HTML, so will apply everywhere.

example:

```
<p id="pli-tv-bu-vb-np2:3.1.11">The robe should be relinquished to a sangha, a group, or an individual. “And, monks, it should be relinquished like this. <span class="pe">(To be expanded as in <a href="/pli-tv-bu-vb-np1#3.2.5">Bu Np 1:3.2.5</a>–3.2.29, with appropriate substitutions.) </span></p>
```

- [x] add domain to links in body text

The same issue is found in the EPUB. Presumably fixing the HTML will also fix the EPUB, but we need to test this.

## in footnotes

Links inside footnotes are correct in the HTML file.

example:

```
<p>“Disregarded the draw” renders <i lang="pi" translate="no">kusaṁ saṅkāmetvā</i>. <i lang="pi" translate="no">Kusa</i>-grass was used to draw lots when distributing robe-cloth, see <a href="https://suttacentral.net/pli-tv-kd8/en/brahmali#9.4.4">Pli Tv Kd 8:9.4.4</a>.  <a epub:type="backlink" href="#noteref-35" role="doc-backlink">↩</a></p>
```

However in the PDF file they are incorrect. The same link goes to `https://suttacentral.net/pli%7B-%7Dtv%7B-%7Dkd8`. This is generated from the following LaTeX code:

```
\href{https://suttacentral.net/pli{-}tv{-}kd8/en/brahmali\#9.4.4}{Pli Tv Kd 8:9.4.4}
```

It looks like it is escaping characters wrongly, so it should be:

```
\href{https://suttacentral.net/pli-tv-kd8/en/brahmali#9.4.4}{Pli Tv Kd 8:9.4.4}
```

- [x] fix malformed links in PDF

**Comment by ihongda** [comment]
> \href{https://suttacentral.net/pli{-}tv{-}kd8/en/brahmali\#9.4.4}{Pli Tv Kd 8:9.4.4}

According to github copilot's suggestion `{-}` is unnecessary, we can use `-` directly

`\href{https://suttacentral.net/pli-tv-kd8/en/brahmali\#9.4.4}{Pli Tv Kd 8:9.4.4}`

**Comment by ihongda** [comment]
https://github.com/suttacentral/editions/tree/main/en/brahmali/pli-tv-vi/paperback
