### ISSUE TITLE
add volume ISBN to book publications

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#2940]
The paperback book publications have two distinct ISBNs.

- publication ISBN applies to *all* books in the set (if there is one)
- volume ISBN applies only to that specific volume.

For example, there is one publication ISBN for the whole Vinaya, and six individual volume ISBNs for each book.

Currently the Volume ISBN is used to generate the barcode on the cover. But the interior metadata only lists the Publication ISBN. 

![Screenshot from 2023-10-31 18-28-56](https://github.com/suttacentral/bilara-data/assets/6112010/91d14084-3ed7-4f0b-92a4-a4a8d8463c90)

We should also list the Volume ISBN in the metadata.

**Comment by ihongda** [comment]
Bhante @sujato , this issue has been resolved.

![截图 2023-11-06 12-47-32](https://github.com/suttacentral/bilara-data/assets/4037966/ebce464b-bc21-4782-8a53-0bbe16909907)
