### ISSUE TITLE
Add scpub number to bilara-data texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara-data#357]
## The problem

Normally a published text will have some metadata for publication details. For example, all of our legacy HTML texts have such a field. The Bilara texts do not, as the publication info is handled in `_publication.json`. 

Unfortunately this means there is no trivial way to check the publication status of a given text. You have to look up `_publication.json` and check the `author_uid` and `text_uid` fields. Then you have to infer the `text_uid` from the segment or file number, i.e. you have to understand that `sn1.44` belongs to `sn`. To do this you either have to parse the ID (clunky and error-prone) or look it up in the `tree` files. 

This is not very useful for someone inspecting the file. And it also means there is no simple hook for linking a text to `_publication.json`.

## The solution

Each publication in `_publication.json` has a unique `publication_number` of the form `scpub3`.

- **Add `_publication_number` field to every bilara-data text.**

This would apply to all texts: root and translation, published and unpublished.

Let's take an example SN 1.44. Currently the en/sujato translation has:

```
{
  "sn1.44:0.1": "Linked Discourses 1 ",
  "sn1.44:0.2": "5. On Fire ",
  "sn1.44:0.3": "44. One Root ",
  "sn1.44:1.1": "“One is the root, two are the whirlpools, ",
  "sn1.44:1.2": "three are the stains, five the spreads, ",
  "sn1.44:1.3": "twelve the ocean’s whirlpools: ",
  "sn1.44:1.4": "such is the abyss crossed over by the hermit.”"
}
```

This would become something like:

```
{
  "sn1.44:0.1": "Linked Discourses 1 ",
  "sn1.44:0.2": "5. On Fire ",
  "sn1.44:0.3": "44. One Root ",
  "sn1.44:1.1": "“One is the root, two are the whirlpools, ",
  "sn1.44:1.2": "three are the stains, five the spreads, ",
  "sn1.44:1.3": "twelve the ocean’s whirlpools: ",
  "sn1.44:1.4": "such is the abyss crossed over by the hermit.”",
  "_publication_number": "scpub4"
}
```

Let the JSON experts determine the proper way to express this! 🙏

Now if you want to learn the publication details, just look up `scpub4` in `_publication.json`. 

## Complications

The most obvious problem is that all our systems are built on the assumption that the Bilara files are straight key/value, and don't understand metadata. So that is one issue, I have no idea how much of a hassle this will be. 

We could work around this by adding the metadata in a separate file, but it seems to me that would only add to the complexity. "For the metadata in a text file, you have to know to look up this file, get the key, then look up `_publication.json`." Might as well just leave out the middle man and go straight to `_publication.json`.

The smaller problem is actually adding the numbers. We could do it by hand to start with, then automate it later.

**Comment by firepick1** [comment]
The proposal to include `"_publication_number": "scpub4"` creates a lot of work since now we would need to add special handling  throughout any code that ever uses translation or root files. It also creates a brittle and unnecessary dependency between individual translation files and publications. 

If the problem we're solving is streamlining access to publication information, the first job should be to define a publication API that works with the existing data. That API should provide for everybody's needs. The API itself may need auxiliary files that are computed and stored in git by Gihub actions. The translation and root file schemas forbid metadata. Publication metadata should go elsewhere. For example, Voice uses generated metadata files such as [suidmap.js](https://github.com/sc-voice/scv-bilara/blob/master/src/auto/suidmap.js). These files are machine generated to simplify API implementation.

**Comment by sujato** [comment]
Thanks Karl for the feedback. Indeed, that is what I feared! 

So let me see if I understand your proposal. 

The first thing is that the association between text and publication status should be explicit and stated in bilara-data. That's because it is relevant not just for Voice or SC, but for any application that uses these texts. We would then import it into the SuttaCentral API (or wherever it is used).

We would create a `publication` API  which essentially would be a set of JSON data that defines the `publication_number` for each text.

Let us take my translation of MN as an example. This is assigned the publication number `scpub3`. In bilara-data, the texts are named with the pattern `mn1_translation-en-sujato.json`. So we could do something like this.

```
[
  {
    "mn1_translation-en-sujato.json": "scpub3"
  },
  {
    "mn2_translation-en-sujato.json": "scpub3"
  },
  {
    "mn3_translation-en-sujato.json": "scpub3"
  }
]
```

This file would be automatically generated via Github Actions every time a new publication was added. 

We need a way to infer the "leaves" from the "root". Given a "root" `an` how do we know what the descendants are? We could look in /translation/en/sujato/sutta/an and list all the .json files. But this is brittle as the folder structure is not always predictable. 

I would feel more comfortable if it were inferred from `mn-tree.json`, which is designed for exactly this kind of thing. Simply list all the leaf nodes in `mn-tree.json`. Currently these files are in sc-data/structure. 

Is that something like what you're thinking?

**Comment by firepick1** [comment]
Yes. The structure you propose would map sutta file names to publication entities. It can be generated from existing data without perturbing that data, thereby ensuring information is stored uniquely. Maps are usually just JSON objects. Perhaps the file might be named `bilara-data/generated/publication-map.json`. The map can even provide additional information as needed, such as publication status:

```
{
    "mn1_translation-en-sujato.json": {
         "pub": "scpub3",
         "published": false,
    },
    ...etc....
}
```

And perhaps this file may have other uses beyond publication. I've found these files to be extremely helpful in coding. Hopefully others may as well.

**Comment by sujato** [comment]
Just to note, I think we will not implement this right away. For now, we can do what we need with a DB query. We will revisit this when developing the system for publishing specific texts.

https://github.com/suttacentral/suttacentral/issues/1519
