### ISSUE TITLE
Corrections to preface and colophon of printed/pdf version

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#3642]
**Preface:**
p.x:  "without whose help this work might never have got published" > "without whose help this work might never have **been** published"

**Colophon:**
Normay > Norway
“Translated from the Pali. Primary source was the” > “Translated from the Pali. **The p**rimary source was the”
2nd line: "reference of other" > "reference **to** other"
3rd last line: "as well Bhikkhu" > "as well **as** Bhikkhu"

**Comment by sujato** [comment]
ok, fixed these.
