### ISSUE TITLE
enlightenment

### ISSUE THREAD

**Issue by xiaoking2593** [suttacentral/bilara-data#3770]
https://github.com/suttacentral/bilara-data/blob/07dc549330ccb7b267edb1ad5e001207064d149c/translation/en/sujato/sutta/mn/mn85_translation-en-sujato.json#L278

**Comment by thesunshade** [comment]
What is this?

If you find a typo, please report it in the feedback category on the forum.

https://discourse.suttacentral.net/c/feedback/19
