### ISSUE TITLE
Inconsistent segment ID pattern, missing separator :

### ISSUE THREAD

**Issue by yapcheahshen** [suttacentral/bilara-data#4]
an1.259.1.1 in an1.258-267_root-Pali-ms.json

an2.4.0.1 in an2.1-10_root-Pali-ms.json

**Comment by sujato** [comment]
You mean they are missing the colon? Yes, this is a mistake, we will fix it.

**Comment by sujato** [comment]
Also:

pli-tv-bi-vb-sk1-75_root-pli-ms.json
pli-tv-bi-vb-sk1:75:0.1 should be pli-tv-bi-vb-sk75:0.1
pli-tv-bi-vb-sk1:75:0.2 should be pli-tv-bi-vb-sk75:0.2

pli-tv-bi-vb-sk1-75_translation-en-brahmali.json
"pli-tv-bi-vb-sk1:75:0.1": "The sub-chapter on shoes ",
"pli-tv-bi-vb-sk1:75:0.2": "75. the training rule on defecating in water ",

**Comment by sujato** [comment]
These appear to be correct.
