### ISSUE TITLE
Corrections to English Vinaya translation

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#660]
Bhante @Sujato, a few things that need to be sorted out in the English Vinaya translation. Here goes:

**Kd.4
Segments 5.6.2 and 5.6.10:** remove (half-)bold both from the Pali and the English.

**6.3.23 and 6.3.24:** remove (full-)bold both from the Pali and the English.

**11.2.23 and 11.2.24 :** add bold to both, and remove separation between the two lines (as elsewhere).

**15.1.0:** Capitalise “invitation”

**Kd.16:
Segments 6.5.4 and 6.5.5:** add bold (as for the previous two segments)

Finally, I am not allowed to edit lines in bilara that do not have a Pali counterpart, such as added headings. Would it be possible to change this, please?

**Comment by sujato** [comment]
I've corrected these and made an issue for the heading translation. 

Meanwhile if you have edits to headings, maybe just pop them on here as a separate issue and I'll do it.

**Comment by sujato** [comment]
Adding these was considerably more complex than I anticipated, because there were changes to the translation in published and unpublished.. Next time, let's make sure the latest changes to unpublished are pushed before doing anything fancy! Anyway, I hope I got it right.

**Comment by brahmali** [comment]
OK, thanks for sorting it out. You know, you are very welcome to push things to published whenever you think it is required. Because I keep on pestering you with changes, yet I have no idea when you will get around to have a look at them, it is probably better if you just do the pushing. I have no problem with this at all.
