### ISSUE TITLE
Pali segments in wrong order 

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#665]
Hi Bhante, at Kd.11 we have a problem with the sequence of the Pali segments. Segment 31.1.165.0 is in the wrong place. It should come directly after segment 31.1.162. Then 31.1.165.1 should be moved up to directly follow 31.1.165.0. Then follows 31.1.163 and everything else is fine.

Should I use this "issue" page for all problems from now on? B

**Comment by sujato** [comment]
I've fixed this, and yes, please leave each correction as an issue.
