### ISSUE TITLE
Fake bullet points in KD.14 + +

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#685]
- On SuttaCentral, Kd.14, the following segments show as bullet points, when in fact they are not supposed to: 12.4.8 to 12.4.19
- In the same Chapter, there is a horizonal rule after segment 14.9.18, when it should be before this segment.
- Still Kd.14: the bullet points in segments 12.5.2-12.5.8 should be structured (not unstructured), as in the parallel at Kd.11 (segments 5.1.3-5.1.20).
- Segment 14.9.18: move hr from after to before this segment.

**Comment by sujato** [comment]
This one has been done
