### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#717]
**Kd.1:**

Segments 20.4.1 and 20.6.1: can these please be shown on the same line when viewing in plain (not side-by-side) mode.

Segments 23.7.1 and 23.10.6: there is a big gap between these (in plain mode).

Segments 24.6.4 and 24.6.9: ditto

**Kd.6:**

Segments 23.4.3 and 23.4.4: again, these should be shown on the same line when viewing in plain mode.

**Kd.9:**

Segment 7.9.14: remove #.

**Comment by sujato** [comment]
>  Kd.1:
>  
>  Segments 20.4.1 and 20.6.1: can these please be shown on the same line when viewing in plain (not side-by-side) mode.

Nope. The problem is that a large chunk of Pali text has been abbreviated, and the paragraph is necessary for that. You need to adjust the translation to fit the paragraph break. Either:

```
  "pli-tv-kd1:20.4.1": "The Buddha told him what had happened, and Uruvelā Kassapa thought, ",
  "pli-tv-kd1:20.6.1": "",
```
or, and this is better IMHO:

```
  "pli-tv-kd1:20.4.1": "The Buddha told him what had happened. ",
  "pli-tv-kd1:20.6.1": "Uruvelā Kassapa thought,",
```

>  Segments 23.7.1 and 23.10.6: there is a big gap between these (in plain mode).
>  
>  Segments 24.6.4 and 24.6.9: ditto

This is a tricky problem. It's caused by the fact that that, when we have no translated text, the HTML is still present on the page (ready for when the root is added). Normally this is not a problem, as empty HTML collapses space. But when it is verse, we use `<br>` tags which explicitly add a line-break. Since these have no function other than to add a line, they keep on working even there's nothing there.

This will have to be fixed by a change in how we use HTML, I will have a think about it. But thanks for raising it, this issue has been nagging me for a while.

>  
>  Kd.6:
>  
>  Segments 23.4.3 and 23.4.4: again, these should be shown on the same line when viewing in plain mode.
>  

Same deal, you'll have to adjust the translation here.
>  Kd.9:
>  
>  Segment 7.9.14: remove #.

Looks like this has been done in Bilara already.

**Comment by brahmali** [comment]
> > Kd.1:
> > Segments 20.4.1 and 20.6.1: can these please be shown on the same line when viewing in plain (not side-by-side) mode.
> 
> Nope. The problem is that a large chunk of Pali text has been abbreviated, and the paragraph is necessary for that. You need to adjust the translation to fit the paragraph break. Either:
> 
> ```
>   "pli-tv-kd1:20.4.1": "The Buddha told him what had happened, and Uruvelā Kassapa thought, ",
>   "pli-tv-kd1:20.6.1": "",
> ```
> 
> or, and this is better IMHO:
> 
> ```
>   "pli-tv-kd1:20.4.1": "The Buddha told him what had happened. ",
>   "pli-tv-kd1:20.6.1": "Uruvelā Kassapa thought,",
> ```

OK. I've done a hybrid of what you suggested. Hopefully it will look right.
> 
> > Segments 23.7.1 and 23.10.6: there is a big gap between these (in plain mode).
> > Segments 24.6.4 and 24.6.9: ditto
> 
> This is a tricky problem. It's caused by the fact that that, when we have no translated text, the HTML is still present on the page (ready for when the root is added). Normally this is not a problem, as empty HTML collapses space. But when it is verse, we use `<br>` tags which explicitly add a line-break. Since these have no function other than to add a line, they keep on working even there's nothing there.
> 
> This will have to be fixed by a change in how we use HTML, I will have a think about it. But thanks for raising it, this issue has been nagging me for a while.
> 
Thanks!

> > Kd.6:
> > Segments 23.4.3 and 23.4.4: again, these should be shown on the same line when viewing in plain mode.
> 
> Same deal, you'll have to adjust the translation here.

No, it's not the same deal. Here there are no Pali segments in between, yet the text breaks in plain view. The bilara-data html has the following:

> "pli-tv-kd6:24.4.3": "{}</p>",

and

> "pli-tv-kd6:24.4.4": "<p>{}",

The paragraph markers should not be there.

> > Kd.9:
> > Segment 7.9.14: remove #.
> 
> Looks like this has been done in Bilara already.

OK and thanks!

**Comment by sujato** [comment]
>No, it's not the same deal. Here there are no Pali segments in between

My bad. I can take the `<p>` out, but just to check, are you sure this is what you want? As it is seems better to me. A paragraph marks a logical break, and here it indicates a shift in time frame "The following morning".

**Comment by brahmali** [comment]
> My bad. I can take the `<p>` out, but just to check, are you sure this is what you want? As it is seems better to me. A paragraph marks a logical break, and here it indicates a shift in time frame "The following morning".

Sorry, I got the segment numbers wrong. It should be 23.4.3 and 23.4.4 (not 24.4.3 and 24.4.4). And there should definitely be no paragraph between these segments.
