### ISSUE TITLE
Issues reported previously, but still unresolved

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#759]
The _bhikkhu-saṅghādisesas_ contain both my old and my new translations. The old one needs to be removed.

_Bhikkhu-pācittiyas_ 1-50 have only my rendering, whereas 51-92 have both my translation as well as I.B. Horner’s. My understanding is that the latter is to be deleted.

_Bhikkhu-pāṭidesanīyas_ and _adhikaraṇasamathas_ have both my translation as well as I.B. Horner’s.

_Bhikkhunī-pārājikas, saṅghādisesas, nissaggiyas, pācittiyas, sekhiyas_, and _adhikaraṇasamathadhammas_ all have both my translation as well as I.B. Horner’s.

_Bhikkhunī-pāṭidesanīyas_ are a bit of a mess. The first one has both translations, the rest just I.B. Horner’s. Moreover, rule 2-8 should be merged into one.

The Khandhakas all have both my translation as well as I.B. Horner’s.

The [contents page for the Khandhakas](https://suttacentral.net/pli-tv-kd), uses IB Horner's chapter headings, rather than mine.

The contents pages for both Vibhaṅgas are a strange mishmash of Pali, generic headings (like "First rule on acknowledgment"), and occasionally my rule renderings. It would be good to get this standardised. Let me know if I can help with this.

**Comment by sujato** [comment]
>The bhikkhu-saṅghādisesas contain both my old and my new translations. The old one needs to be removed.

Done.

***

As far as Horner's translation, we didn't have a definite plan, but my thought was that we should keep her original translation in the HTML, just as we have legacy translations of suttas. 

The important thing then would be to make sure that it is in fact *her* text, not one that you have worked on.

What I might do is go back to the original HTML files for her translation and re-generate the legacy texts from there.

Meanwhile, if either your old or mixed translations that you want removed are there, let me know and I'll delete them.

***

I've attended to the bi-pd situation, and I think it should work ok.

The contents pages look okay to me, perhaps it has been fixed in the meantime. Let me know if there are still errors.

**Comment by brahmali** [comment]
> > The bhikkhu-saṅghādisesas contain both my old and my new translations. The old one needs to be removed.
> 
> Done.
> 
> As far as Horner's translation, we didn't have a definite plan, but my thought was that we should keep her original translation in the HTML, just as we have legacy translations of suttas.
> 
OK. I agree this is a good idea.

> The important thing then would be to make sure that it is in fact _her_ text, not one that you have worked on.

I don't believe there is any mish-mash. It is true that I started out working to improve and supplement her translation, but I quickly realised it was not going to work. My memory is a bit vague, but I think I started my own translation at the latest while I was working on the _saṅghādisesas_. So I don't think you have re-generate much, if anything.
> 
> What I might do is go back to the original HTML files for her translation and re-generate the legacy texts from there.
> 
> Meanwhile, if either your old or mixed translations that you want removed are there, let me know and I'll delete them.

This seems to be all done now.
> 
> I've attended to the bi-pd situation, and I think it should work ok.
> 
> The contents pages look okay to me, perhaps it has been fixed in the meantime. Let me know if there are still errors.

There are still lots of problems with content pages. The titles should match the titles I have in the actual rules. The _saṅghādisesa_ rules are all correct and should be used as a model for the rest of the rules. For instance, the contents page should be changed as follows:

**Pārājika**
The rule names should be in English rather than Pali: "The first (second/third/fourth) training rule on expulsion". The Pali name should then show underneath, as it does for the _Saṅhādisesas_.

**Aniyata**
Same problem as for the _pārājikas_. Rule names: "The first (second) undetermined training rule".

**Nissaggiyas and Pācittiyas** 
Again, the same problem as for the _pārājikas_. The rule names need to be taken from the translated text. For the _pācittiyas_ there are two different patterns, both wrong.

**Pāṭidesanīya**
Rule names are wrong. They should be: "The first (second, etc.) training rule on acknowledgment". Pluss delete Pali name next to English. Leave Pali name underneath.

**Sekhiya and Adhikaraṇa**
Same problem as for _pārājikas_.

I will stop there because I am sure get the idea. The above problems are found throughout the Bhikkhunī-vibhaṅga and also the Khandhakas.

**Comment by sujato** [comment]
> problems with content pages

Sorry, I think we're talking at cross-purposes here. I was speaking of the *tables of contents* for each text, which appear to be correct.

I think you're speaking of the sutta cards in the navigation, which as you say, are full of problems in the Vinaya. I will make sure this is sorted out.

**Comment by sujato** [comment]
I'll also make a new project to translate all the titles for the Vinayas, see the ticket here:

https://github.com/suttacentral/suttacentral/issues/2195
