### ISSUE TITLE
One small verse (Iti) in english translations seems to contain wrong word

### ISSUE THREAD

**Issue by olastor** [suttacentral/bilara-data#792]
I stumbled over [this verse](https://github.com/suttacentral/bilara-data/blob/published/translation/en/sujato/sutta/kn/iti/vagga3/iti21_translation-en-sujato.json#L24) on SC and it does not make sense (semantically). I think the word "corruption" might be a copy & paste artifact [from the previous text](https://github.com/suttacentral/bilara-data/blob/published/translation/en/sujato/sutta/kn/iti/vagga2/iti20_translation-en-sujato.json#L24) where it says afterwards "sentient beings go to a bad place". I hope this is the right place to report this.

**Comment by sujato** [comment]
Thanks, I believe this is fixed now. 

error reports are always welcome, we have a dedicated thread for it: https://discourse.suttacentral.net/t/fill-us-with-happiness-tell-us-about-all-our-mistakes/25453/16

It's helpful to include the actual text, so i can be sure it hasn't changed in the meantime.
