### ISSUE TITLE
Wrong segment break in Pali

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#852]
For _bhikkhu-pācittiya_ 27, segments 3.1.16 and 3.1.17 now break like this:

> _Satthagamanīyo nāma_ + _maggo na sakkā hoti vinā satthena gantuṁ._

The break should be like this:

> _Satthagamanīyo nāma maggo_ + _na sakkā hoti vinā satthena gantuṁ._

**Comment by sujato** [comment]
done, thx
