### ISSUE TITLE
Segments I am not allowed to edit

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#964]
pli-tv-kd11: 33.1.69.18: "He should not wear the robes of the ascetics of other sects." > "He should not wear the robes of the monastics of other sects."
pli-tv-kd11: 33.1.69.19: "He should not associate with the ascetics of other sects." > "He should not associate with the monastics of other sects."

pli-tv-kd14: 14.33.41.2: "‘Please, Venerables, I ask the Sangha to listen. While we were arguing and disputing, we did and said many things unworthy of an ascetic. ..." > "Please, Venerables, I ask the Sangha to listen. While we were arguing and disputing, we did and said many things unworthy of a monastic. ..."
pli-tv-kd14: 14.33.41.3: "‘Please, Venerables, I ask the Sangha to listen. While we were arguing and disputing, we did and said many things unworthy of an ascetic. ..." > "‘Please, Venerables, I ask the Sangha to listen. While we were arguing and disputing, we did and said many things unworthy of a monastic. ..."

**Comment by sujato** [comment]
fixed, will propagate next time you update.
