### ISSUE TITLE
More segments I am not allowed to edit

### ISSUE THREAD

**Issue by brahmali** [suttacentral/bilara-data#967]
pli-tv-bu-vb-pj1:9.3.0: "Forced sexual intercourse: bringing the partner into the presence of the monk" > "Forced sexual intercourse: bringing the partner to the monk "
pli-tv-bu-vb-pj1:9.4.0: "Forced sexual intercourse with cover: bringing the partner into the presence of the monk" > "Forced sexual intercourse with cover: bringing the partner to the monk"
pli-tv-bu-vb-pj1:9.5.0: "Forced sexual intercourse: bringing the monk into the presence of the partner " > "Forced sexual intercourse: bringing the monk to the partner"
pli-tv-bu-vb-pj1:9.6.0: "Forced sexual intercourse with cover: bringing the monk into the presence of the partner" > "Forced sexual intercourse with cover: bringing the monk to the partner"

**Comment by sujato** [comment]
I've made these changes. They are in /unpublished, and they should propagate to /published next time you update them.

Small point: if the goal is concision (which in headings it should be) then why not use the normal English word: rape.
